#!/usr/bin/env ruby
# frozen_string_literal: true

# Critical-path, hotspot and priority analysis for docs/planning/backlog/*.yaml.
#
#   ruby tools/planning/critical_path.rb           # print report
#   ruby tools/planning/critical_path.rb --write   # also rewrite generated sections in roadmap.md
#   ruby tools/planning/critical_path.rb --check   # exit 1 on priority inversions, uncovered exit rows
#                                                  # or stale roadmap.md
#
# Model: effort-weighted longest path, size S = 0.5, M = 1.5, L = 4 days, unlimited parallelism.
# Per phase, dependencies on earlier phases count as done (phases are gated, see roadmap.md).
# "Exit path" uses only P0 issues (what gates the phase exit); "all" includes P1/P2.
# An issue's phase is `lands_in_phase` when set (see backlog/SCHEMA.md), else its epic's phase.
# Exit coverage: every row of traceability.md section (b) must cite at least one P0 issue
# (rows marked "(optional)" are skipped).

require 'yaml'

ROOT = File.expand_path('../..', __dir__)
ROADMAP = File.join(ROOT, 'docs/planning/roadmap.md')
TRACEABILITY = File.join(ROOT, 'docs/planning/traceability.md')
DAYS = { 'S' => 0.5, 'M' => 1.5, 'L' => 4.0 }.freeze
PRIORITY_RANK = { 'P0' => 0, 'P1' => 1, 'P2' => 2 }.freeze
HOTSPOT_LIMIT = 10

Issue = Struct.new(:id, :title, :priority, :size, :type, :phase, :epic, :deps, :platforms, keyword_init: true) do
  def days = DAYS.fetch(size)

  # Android and macOS work can proceed in parallel; everything else is shared.
  def track
    plats = platforms & %w[android macos]
    plats.size == 1 && title.start_with?("[#{plats.first}]") ? plats.first : 'shared'
  end
end

def load_issues
  Dir[File.join(ROOT, 'docs/planning/backlog/phase-*.yaml')].sort.flat_map do |path|
    doc = YAML.load_file(path)
    Array(doc['epics']).flat_map do |e|
      Array(e['issues']).map do |i|
        Issue.new(id: i['id'], title: i['title'], priority: i['priority'], size: i['size'], type: i['type'],
                  phase: i['lands_in_phase'] || doc['phase'], epic: e['id'], deps: Array(i['depends_on']),
                  platforms: Array(i['platforms']))
      end
    end
  end
end

ISSUES = load_issues.to_h { |i| [i.id, i] }.freeze

# Longest weighted path through `nodes`; edges leaving the set are ignored.
def longest_path(nodes)
  set = nodes.to_h { |i| [i.id, i] }
  memo = {}
  finish = lambda do |id|
    memo[id] ||= begin
      preds = set[id].deps.select { |d| set.key?(d) }
      best = preds.max_by { |d| finish.call(d).first }
      best ? [finish.call(best).first + set[id].days, finish.call(best).last + [id]] : [set[id].days, [id]]
    end
  end
  set.keys.map { |id| finish.call(id) }.max_by(&:first) || [0, []]
end

def phases = ISSUES.values.map(&:phase).uniq.sort

def phase_issues(phase, p0_only:)
  ISSUES.values.select { |i| i.phase == phase && (!p0_only || i.priority == 'P0') }
end

def dependents = @dependents ||= ISSUES.values.each_with_object(Hash.new { |h, k| h[k] = [] }) do |i, acc|
  i.deps.each { |d| acc[d] << i.id }
end

def priority_inversions
  ISSUES.values.flat_map do |i|
    i.deps.filter_map do |d|
      dep = ISSUES[d]
      "#{i.id} (#{i.priority}) depends on #{d} (#{dep.priority})" if dep && PRIORITY_RANK[dep.priority] > PRIORITY_RANK[i.priority]
    end
  end
end

def uncovered_exit_rows
  section = File.read(TRACEABILITY)[/^## \(b\).*?(?=^## \(c\))/m].to_s
  section.lines.grep(/^\| /).reject { |l| l =~ /^\| (Criterion|---)/ || l.include?('(optional)') }.filter_map do |row|
    ids = row.scan(/\bE\d{2}-\d{2}\b/)
    "#{row.split('|')[1].strip} (cites #{ids.join(', ')})" if ids.none? { |id| ISSUES[id]&.priority == 'P0' }
  end
end

def track_section
  out = +"| Phase | android | macos | shared (protocol, docs, tools, ci, cross) |\n|---|---|---|---|\n"
  phases.each do |ph|
    by = phase_issues(ph, p0_only: true).group_by(&:track).transform_values { |l| l.sum(&:days) }
    out << "| #{ph} | #{fmt_days(by.fetch('android', 0))} | #{fmt_days(by.fetch('macos', 0))} | " \
           "#{fmt_days(by.fetch('shared', 0))} |\n"
  end
  out
end

def fmt_days(days) = format('%.1f d', days)

def chain_table(chain)
  rows = chain.map { |id| "| #{id} | #{ISSUES[id].size} | #{ISSUES[id].title.gsub('|', '\\|')} |" }
  ['| ID | Size | Title |', '|---|---|---|', *rows].join("\n")
end

def critical_path_section
  out = +"Generated by `ruby tools/planning/critical_path.rb --write` (S = 0.5, M = 1.5, L = 4 days,\n" \
         "unlimited parallelism; earlier-phase work counts as done). **Exit path** = longest chain of P0\n" \
         "issues (gates the phase checklist); **all** includes P1/P2.\n\n"
  out << "| Phase | P0 issues | Exit path | All issues | Sum of P0 effort |\n|---|---|---|---|---|\n"
  phases.each do |ph|
    p0 = phase_issues(ph, p0_only: true)
    out << "| #{ph} | #{p0.size} | #{fmt_days(longest_path(p0).first)} | " \
           "#{fmt_days(longest_path(phase_issues(ph, p0_only: false)).first)} | #{fmt_days(p0.sum(&:days))} |\n"
  end
  gated = phases.sum { |ph| longest_path(phase_issues(ph, p0_only: true)).first }
  overall = longest_path(ISSUES.values.select { |i| i.priority == 'P0' })
  out << "\nPhase-gated total (sum of exit paths): **#{fmt_days(gated)}**. Ungated longest P0 chain across all\n" \
         "phases: #{fmt_days(overall.first)} (#{overall.last.first} → … → #{overall.last.last}).\n"
  phases.each do |ph|
    days, chain = longest_path(phase_issues(ph, p0_only: true))
    out << "\n#### Phase #{ph} exit path — #{fmt_days(days)}\n\n#{chain_table(chain)}\n"
  end
  out
end

def hotspot_section
  fan_in = ISSUES.values.sort_by { |i| [-i.deps.size, i.id] }.first(HOTSPOT_LIMIT)
  fan_out = ISSUES.values.sort_by { |i| [-dependents[i.id].size, i.id] }.first(HOTSPOT_LIMIT)
  out = +"| Fan-out (most dependents) | n | Fan-in (most dependencies) | n |\n|---|---|---|---|\n"
  fan_out.zip(fan_in).each do |o, i|
    out << "| #{o.id} #{o.title.gsub('|', '\\|')} | #{dependents[o.id].size} | " \
           "#{i.id} #{i.title.gsub('|', '\\|')} | #{i.deps.size} |\n"
  end
  out
end

def epic_graph_section
  epics = ISSUES.values.group_by(&:epic)
  edges = Hash.new { |h, k| h[k] = [] }
  ISSUES.values.each do |i|
    i.deps.each { |d| edges[ISSUES[d].epic] << i.epic if ISSUES[d] && ISSUES[d].epic != i.epic }
  end
  out = +"```mermaid\nflowchart LR\n"
  epics.keys.group_by { |e| epics[e].first.phase }.sort.each do |ph, list|
    out << "  subgraph P#{ph}[Phase #{ph}]\n"
    list.sort.each { |e| out << "    #{e}\n" }
    out << "  end\n"
  end
  edges.sort.each { |from, tos| out << "  #{from} --> #{tos.uniq.sort.join(' & ')}\n" }
  out << "```\n"
end

SECTIONS = {
  'critical-path' => :critical_path_section,
  'hotspots' => :hotspot_section,
  'epic-graph' => :epic_graph_section,
  'tracks' => :track_section
}.freeze

def regenerate(text)
  SECTIONS.reduce(text) do |acc, (name, gen)|
    pattern = /(<!-- BEGIN GENERATED: #{name} -->\n).*?(<!-- END GENERATED: #{name} -->)/m
    raise "roadmap.md: missing generated section #{name}" unless acc.match?(pattern)

    acc.sub(pattern) { "#{Regexp.last_match(1)}#{send(gen)}#{Regexp.last_match(2)}" }
  end
end

inversions = priority_inversions
uncovered = uncovered_exit_rows
if ARGV.include?('--write') || ARGV.include?('--check')
  text = File.read(ROADMAP)
  fresh = regenerate(text)
  if ARGV.include?('--write')
    File.write(ROADMAP, fresh)
    puts 'wrote docs/planning/roadmap.md generated sections'
  elsif fresh != text
    abort('✗ roadmap.md generated sections are stale; run with --write')
  end
else
  puts critical_path_section, '', hotspot_section, '', track_section
end
unless uncovered.empty?
  warn uncovered.map { |x| "✗ exit row without a P0 issue: #{x}" }.join("\n")
  exit 1
end
unless inversions.empty?
  warn inversions.map { |x| "✗ priority inversion: #{x}" }.join("\n")
  exit 1
end
puts "✓ no priority inversions; every exit row covered by a P0 issue (#{ISSUES.size} issues)"
