"""pytest suite for tools/pcap-audit/canary_scan.py (E15-06 tdd entries).

tdd:
  unit: canaryScan_canaryInSingleTcpPayload_exitsOneWithFrameNumber
  unit: canaryScan_canarySplitAcrossTwoSegments_detectedInReassembledStream
  unit: canaryScan_canaryOnNonTandemPort_exitsOne
  unit: canaryScan_tls13FixtureWithoutCanary_exitsZero
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import canary_scan

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"
TOOL = Path(__file__).resolve().parents[1] / "canary_scan.py"

# Generated by fixtures/regenerate.sh; not a secret, just fixed structural test data.
CANARY = "TANDEM-CANARY-0123456789abcdef0123456789abcdef"


def test_canaryScan_canaryInSingleTcpPayload_exitsOneWithFrameNumber():
    result = canary_scan.scan_for_canary(FIXTURES / "canary-single-payload.pcapng", CANARY)

    assert result["result"] == "fail"
    assert result["occurrences"] == 1
    assert result["frameHits"] == [4]


def test_canaryScan_canarySplitAcrossTwoSegments_detectedInReassembledStream():
    result = canary_scan.scan_for_canary(FIXTURES / "canary-split-segments.pcapng", CANARY)

    assert result["result"] == "fail"
    assert result["occurrences"] == 1
    # Neither individual segment carries the whole canary; it's only found once the TCP stream
    # is reassembled.
    assert result["frameHits"] == []
    assert len(result["streamHits"]) == 1
    assert len(result["streamHits"][0]["frames"]) >= 2


def test_canaryScan_canaryOnNonTandemPort_exitsOne():
    result = canary_scan.scan_for_canary(FIXTURES / "canary-non-tandem-port.pcapng", CANARY)

    assert result["result"] == "fail"
    assert result["occurrences"] == 1
    assert result["frameHits"]


def test_canaryScan_tls13FixtureWithoutCanary_exitsZero():
    result = canary_scan.scan_for_canary(FIXTURES / "tls13-handshake.pcapng", CANARY)

    assert result == {"result": "pass", "occurrences": 0}


def test_canaryScan_cli_exitStatusMatchesResult():
    ok = subprocess.run(
        [sys.executable, str(TOOL), str(FIXTURES / "tls13-handshake.pcapng"), "--canary", CANARY],
        capture_output=True,
        text=True,
    )
    assert ok.returncode == 0

    failing = subprocess.run(
        [
            sys.executable,
            str(TOOL),
            str(FIXTURES / "canary-single-payload.pcapng"),
            "--canary",
            CANARY,
        ],
        capture_output=True,
        text=True,
    )
    assert failing.returncode == 1
