// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/calls.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface CallEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.CallEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string call_id = 1 [json_name = "callId"];</code>
   * @return The callId.
   */
  java.lang.String getCallId();
  /**
   * <code>string call_id = 1 [json_name = "callId"];</code>
   * @return The bytes for callId.
   */
  com.google.protobuf.ByteString
      getCallIdBytes();

  /**
   * <code>.tandem.v1.CallDirection direction = 2 [json_name = "direction"];</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>.tandem.v1.CallDirection direction = 2 [json_name = "direction"];</code>
   * @return The direction.
   */
  dev.tandem.protocol.v1.CallDirection getDirection();

  /**
   * <code>.tandem.v1.CallState state = 3 [json_name = "state"];</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.tandem.v1.CallState state = 3 [json_name = "state"];</code>
   * @return The state.
   */
  dev.tandem.protocol.v1.CallState getState();

  /**
   * <code>string address = 4 [json_name = "address"];</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 4 [json_name = "address"];</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string normalized_e164 = 5 [json_name = "normalizedE164"];</code>
   * @return The normalizedE164.
   */
  java.lang.String getNormalizedE164();
  /**
   * <code>string normalized_e164 = 5 [json_name = "normalizedE164"];</code>
   * @return The bytes for normalizedE164.
   */
  com.google.protobuf.ByteString
      getNormalizedE164Bytes();

  /**
   * <code>uint64 timestamp_ms = 6 [json_name = "timestampMs"];</code>
   * @return The timestampMs.
   */
  long getTimestampMs();
}
