// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/clipboard.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface ClipboardTextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.ClipboardText)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Identifies which side last wrote this clipboard content: "macos" or "android" (E31-04,
   * E31-06). A plain string rather than an enum (unlike NotificationDismiss.Origin/
   * RingStop.Origin) because it is only ever compared for equality by the E31-08/E31-14 loop
   * guard, never branched on by value. Used together with content_hash (below) for echo-loop
   * prevention (docs/protocol/SPEC.md #clipboard-channel).
   * </pre>
   *
   * <code>string origin_tag = 1 [json_name = "originTag"];</code>
   * @return The originTag.
   */
  java.lang.String getOriginTag();
  /**
   * <pre>
   * Identifies which side last wrote this clipboard content: "macos" or "android" (E31-04,
   * E31-06). A plain string rather than an enum (unlike NotificationDismiss.Origin/
   * RingStop.Origin) because it is only ever compared for equality by the E31-08/E31-14 loop
   * guard, never branched on by value. Used together with content_hash (below) for echo-loop
   * prevention (docs/protocol/SPEC.md #clipboard-channel).
   * </pre>
   *
   * <code>string origin_tag = 1 [json_name = "originTag"];</code>
   * @return The bytes for originTag.
   */
  com.google.protobuf.ByteString
      getOriginTagBytes();

  /**
   * <pre>
   * SHA-256 digest (32 bytes) of `text`'s UTF-8 bytes (docs/protocol/SPEC.md #clipboard-channel).
   * Paired with origin_tag by the E31-08/E31-14 loop guard: a side that receives and writes a
   * clip records this pair, so when its own poller re-detects the same content it recognizes its
   * own just-written content and does not send it back.
   * </pre>
   *
   * <code>bytes content_hash = 2 [json_name = "contentHash"];</code>
   * @return The contentHash.
   */
  com.google.protobuf.ByteString getContentHash();

  /**
   * <pre>
   * UTF-8 clipboard text. Hard cap: exactly 1,048,576 bytes (1 MiB;
   * docs/protocol/SPEC.md #timeouts-connection-limits-and-resource-caps "Feature caps" and
   * #clipboard-channel). Oversize text MUST be rejected, never truncated (E31-04, E31-06).
   * </pre>
   *
   * <code>string text = 3 [json_name = "text"];</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * UTF-8 clipboard text. Hard cap: exactly 1,048,576 bytes (1 MiB;
   * docs/protocol/SPEC.md #timeouts-connection-limits-and-resource-caps "Feature caps" and
   * #clipboard-channel). Oversize text MUST be rejected, never truncated (E31-04, E31-06).
   * </pre>
   *
   * <code>string text = 3 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * True when this content originated from a source the sender treats as sensitive (e.g. an
   * Android password manager setting EXTRA_IS_SENSITIVE; PRD F-6.2, F-6.3). A receiver writes a
   * sensitive clip with the org.nspasteboard.ConcealedType and org.nspasteboard.TransientType
   * markers (E31-13) so clipboard managers and this protocol's own poller skip it. `text` is
   * never written to a log in a release build (invariant 7) regardless of this flag's value.
   * </pre>
   *
   * <code>bool sensitive = 4 [json_name = "sensitive"];</code>
   * @return The sensitive.
   */
  boolean getSensitive();
}
