// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/contacts.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface ContactsSyncResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.ContactsSyncResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  dev.tandem.protocol.v1.ContactsSyncStatus getStatus();

  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  java.util.List<dev.tandem.protocol.v1.Contact> 
      getContactsList();
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  dev.tandem.protocol.v1.Contact getContacts(int index);
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  int getContactsCount();

  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @return A list containing the deletedContactIds.
   */
  java.util.List<java.lang.String>
      getDeletedContactIdsList();
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @return The count of deletedContactIds.
   */
  int getDeletedContactIdsCount();
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @param index The index of the element to return.
   * @return The deletedContactIds at the given index.
   */
  java.lang.String getDeletedContactIds(int index);
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @param index The index of the element to return.
   * @return The deletedContactIds at the given index.
   */
  com.google.protobuf.ByteString
      getDeletedContactIdsBytes(int index);

  /**
   * <code>uint64 watermark_ms = 4 [json_name = "watermarkMs"];</code>
   * @return The watermarkMs.
   */
  long getWatermarkMs();

  /**
   * <code>bool complete = 5 [json_name = "complete"];</code>
   * @return The complete.
   */
  boolean getComplete();
}
