// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/contacts.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * ContactsSyncResponse: PRD F-8.3, UC-18, UC-19, UC-20, UC-21 -- the phone's answer to a
 * ContactsSyncRequest, possibly paginated (`complete = false` while more pages follow;
 * docs/protocol/SPEC.md #contacts-channel "Sync"). `deletedContactIds` names contacts removed from
 * the phone's store since `sinceUpdatedAtMs` (tombstones, UC-20). `watermarkMs` is the
 * Mac-authoritative watermark the Mac should persist and echo back as the next
 * ContactsSyncRequest.sinceUpdatedAtMs once `complete = true` (docs/protocol/SPEC.md
 * #contacts-channel "Watermark").
 * </pre>
 *
 * Protobuf type {@code tandem.v1.ContactsSyncResponse}
 */
@com.google.protobuf.Generated
public  final class ContactsSyncResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ContactsSyncResponse, ContactsSyncResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.ContactsSyncResponse)
    ContactsSyncResponseOrBuilder {
  private ContactsSyncResponse() {
    contacts_ = emptyProtobufList();
    deletedContactIds_ = emptyProtobufList();
  }
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.ContactsSyncStatus getStatus() {
    dev.tandem.protocol.v1.ContactsSyncStatus result = dev.tandem.protocol.v1.ContactsSyncStatus.forNumber(status_);
    return result == null ? dev.tandem.protocol.v1.ContactsSyncStatus.UNRECOGNIZED : result;
  }
  /**
   * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
   * @param value The enum numeric value on the wire for status to set.
   */
  private void setStatusValue(int value) {
      status_ = value;
  }
  /**
   * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
   * @param value The status to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setStatus(dev.tandem.protocol.v1.ContactsSyncStatus value) {
    status_ = value.getNumber();

  }
  /**
   * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
   */
  private void clearStatus() {

    status_ = 0;
  }

  public static final int CONTACTS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<dev.tandem.protocol.v1.Contact> contacts_;
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  @java.lang.Override
  public java.util.List<dev.tandem.protocol.v1.Contact> getContactsList() {
    return contacts_;
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  public java.util.List<? extends dev.tandem.protocol.v1.ContactOrBuilder> 
      getContactsOrBuilderList() {
    return contacts_;
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  @java.lang.Override
  public int getContactsCount() {
    return contacts_.size();
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.Contact getContacts(int index) {
    return contacts_.get(index);
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  public dev.tandem.protocol.v1.ContactOrBuilder getContactsOrBuilder(
      int index) {
    return contacts_.get(index);
  }
  private void ensureContactsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.tandem.protocol.v1.Contact> tmp = contacts_;
    if (!tmp.isModifiable()) {
      contacts_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setContacts(
      int index, dev.tandem.protocol.v1.Contact value) {
    value.getClass();  // minimal bytecode null check
    ensureContactsIsMutable();
    contacts_.set(index, value);
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addContacts(dev.tandem.protocol.v1.Contact value) {
    value.getClass();  // minimal bytecode null check
    ensureContactsIsMutable();
    contacts_.add(value);
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addContacts(
      int index, dev.tandem.protocol.v1.Contact value) {
    value.getClass();  // minimal bytecode null check
    ensureContactsIsMutable();
    contacts_.add(index, value);
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  private void addAllContacts(
      java.lang.Iterable<? extends dev.tandem.protocol.v1.Contact> values) {
    ensureContactsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, contacts_);
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  private void clearContacts() {
    contacts_ = emptyProtobufList();
  }
  /**
   * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
   */
  private void removeContacts(int index) {
    ensureContactsIsMutable();
    contacts_.remove(index);
  }

  public static final int DELETED_CONTACT_IDS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> deletedContactIds_;
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @return A list containing the deletedContactIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getDeletedContactIdsList() {
    return deletedContactIds_;
  }
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @return The count of deletedContactIds.
   */
  @java.lang.Override
  public int getDeletedContactIdsCount() {
    return deletedContactIds_.size();
  }
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @param index The index of the element to return.
   * @return The deletedContactIds at the given index.
   */
  @java.lang.Override
  public java.lang.String getDeletedContactIds(int index) {
    return deletedContactIds_.get(index);
  }
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the deletedContactIds at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeletedContactIdsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        deletedContactIds_.get(index));
  }
  private void ensureDeletedContactIdsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        deletedContactIds_;  if (!tmp.isModifiable()) {
      deletedContactIds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @param index The index to set the value at.
   * @param value The deletedContactIds to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDeletedContactIds(
      int index, java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureDeletedContactIdsIsMutable();
    deletedContactIds_.set(index, value);
  }
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @param value The deletedContactIds to add.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addDeletedContactIds(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureDeletedContactIdsIsMutable();
    deletedContactIds_.add(value);
  }
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @param values The deletedContactIds to add.
   */
  private void addAllDeletedContactIds(
      java.lang.Iterable<java.lang.String> values) {
    ensureDeletedContactIdsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, deletedContactIds_);
  }
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   */
  private void clearDeletedContactIds() {
    deletedContactIds_ = emptyProtobufList();
  }
  /**
   * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
   * @param value The bytes of the deletedContactIds to add.
   */
  private void addDeletedContactIdsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureDeletedContactIdsIsMutable();
    deletedContactIds_.add(value.toStringUtf8());
  }

  public static final int WATERMARK_MS_FIELD_NUMBER = 4;
  private long watermarkMs_;
  /**
   * <code>uint64 watermark_ms = 4 [json_name = "watermarkMs"];</code>
   * @return The watermarkMs.
   */
  @java.lang.Override
  public long getWatermarkMs() {
    return watermarkMs_;
  }
  /**
   * <code>uint64 watermark_ms = 4 [json_name = "watermarkMs"];</code>
   * @param value The watermarkMs to set.
   */
  private void setWatermarkMs(long value) {
    
    watermarkMs_ = value;
  }
  /**
   * <code>uint64 watermark_ms = 4 [json_name = "watermarkMs"];</code>
   */
  private void clearWatermarkMs() {

    watermarkMs_ = 0L;
  }

  public static final int COMPLETE_FIELD_NUMBER = 5;
  private boolean complete_;
  /**
   * <code>bool complete = 5 [json_name = "complete"];</code>
   * @return The complete.
   */
  @java.lang.Override
  public boolean getComplete() {
    return complete_;
  }
  /**
   * <code>bool complete = 5 [json_name = "complete"];</code>
   * @param value The complete to set.
   */
  private void setComplete(boolean value) {
    
    complete_ = value;
  }
  /**
   * <code>bool complete = 5 [json_name = "complete"];</code>
   */
  private void clearComplete() {

    complete_ = false;
  }

  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.ContactsSyncResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.ContactsSyncResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.ContactsSyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.ContactsSyncResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ContactsSyncResponse: PRD F-8.3, UC-18, UC-19, UC-20, UC-21 -- the phone's answer to a
   * ContactsSyncRequest, possibly paginated (`complete = false` while more pages follow;
   * docs/protocol/SPEC.md #contacts-channel "Sync"). `deletedContactIds` names contacts removed from
   * the phone's store since `sinceUpdatedAtMs` (tombstones, UC-20). `watermarkMs` is the
   * Mac-authoritative watermark the Mac should persist and echo back as the next
   * ContactsSyncRequest.sinceUpdatedAtMs once `complete = true` (docs/protocol/SPEC.md
   * #contacts-channel "Watermark").
   * </pre>
   *
   * Protobuf type {@code tandem.v1.ContactsSyncResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.ContactsSyncResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.ContactsSyncResponse)
      dev.tandem.protocol.v1.ContactsSyncResponseOrBuilder {
    // Construct using dev.tandem.protocol.v1.ContactsSyncResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return instance.getStatusValue();
    }
    /**
     * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
     * @param value The status to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      copyOnWrite();
      instance.setStatusValue(value);
      return this;
    }
    /**
     * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.ContactsSyncStatus getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(dev.tandem.protocol.v1.ContactsSyncStatus value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    @java.lang.Override
    public java.util.List<dev.tandem.protocol.v1.Contact> getContactsList() {
      return java.util.Collections.unmodifiableList(
          instance.getContactsList());
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    @java.lang.Override
    public int getContactsCount() {
      return instance.getContactsCount();
    }/**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.Contact getContacts(int index) {
      return instance.getContacts(index);
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder setContacts(
        int index, dev.tandem.protocol.v1.Contact value) {
      copyOnWrite();
      instance.setContacts(index, value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder setContacts(
        int index, dev.tandem.protocol.v1.Contact.Builder builderForValue) {
      copyOnWrite();
      instance.setContacts(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder addContacts(dev.tandem.protocol.v1.Contact value) {
      copyOnWrite();
      instance.addContacts(value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder addContacts(
        int index, dev.tandem.protocol.v1.Contact value) {
      copyOnWrite();
      instance.addContacts(index, value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder addContacts(
        dev.tandem.protocol.v1.Contact.Builder builderForValue) {
      copyOnWrite();
      instance.addContacts(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder addContacts(
        int index, dev.tandem.protocol.v1.Contact.Builder builderForValue) {
      copyOnWrite();
      instance.addContacts(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder addAllContacts(
        java.lang.Iterable<? extends dev.tandem.protocol.v1.Contact> values) {
      copyOnWrite();
      instance.addAllContacts(values);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder clearContacts() {
      copyOnWrite();
      instance.clearContacts();
      return this;
    }
    /**
     * <code>repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];</code>
     */
    public Builder removeContacts(int index) {
      copyOnWrite();
      instance.removeContacts(index);
      return this;
    }

    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @return A list containing the deletedContactIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getDeletedContactIdsList() {
      return java.util.Collections.unmodifiableList(
          instance.getDeletedContactIdsList());
    }
    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @return The count of deletedContactIds.
     */
    @java.lang.Override
    public int getDeletedContactIdsCount() {
      return instance.getDeletedContactIdsCount();
    }
    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @param index The index of the element to return.
     * @return The deletedContactIds at the given index.
     */
    @java.lang.Override
    public java.lang.String getDeletedContactIds(int index) {
      return instance.getDeletedContactIds(index);
    }
    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the deletedContactIds at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeletedContactIdsBytes(int index) {
      return instance.getDeletedContactIdsBytes(index);
    }
    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @param index The index to set the value at.
     * @param value The deletedContactIds to set.
     * @return This builder for chaining.
     */
    public Builder setDeletedContactIds(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setDeletedContactIds(index, value);
      return this;
    }
    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @param value The deletedContactIds to add.
     * @return This builder for chaining.
     */
    public Builder addDeletedContactIds(
        java.lang.String value) {
      copyOnWrite();
      instance.addDeletedContactIds(value);
      return this;
    }
    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @param values The deletedContactIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllDeletedContactIds(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllDeletedContactIds(values);
      return this;
    }
    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeletedContactIds() {
      copyOnWrite();
      instance.clearDeletedContactIds();
      return this;
    }
    /**
     * <code>repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];</code>
     * @param value The bytes of the deletedContactIds to add.
     * @return This builder for chaining.
     */
    public Builder addDeletedContactIdsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addDeletedContactIdsBytes(value);
      return this;
    }

    /**
     * <code>uint64 watermark_ms = 4 [json_name = "watermarkMs"];</code>
     * @return The watermarkMs.
     */
    @java.lang.Override
    public long getWatermarkMs() {
      return instance.getWatermarkMs();
    }
    /**
     * <code>uint64 watermark_ms = 4 [json_name = "watermarkMs"];</code>
     * @param value The watermarkMs to set.
     * @return This builder for chaining.
     */
    public Builder setWatermarkMs(long value) {
      copyOnWrite();
      instance.setWatermarkMs(value);
      return this;
    }
    /**
     * <code>uint64 watermark_ms = 4 [json_name = "watermarkMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWatermarkMs() {
      copyOnWrite();
      instance.clearWatermarkMs();
      return this;
    }

    /**
     * <code>bool complete = 5 [json_name = "complete"];</code>
     * @return The complete.
     */
    @java.lang.Override
    public boolean getComplete() {
      return instance.getComplete();
    }
    /**
     * <code>bool complete = 5 [json_name = "complete"];</code>
     * @param value The complete to set.
     * @return This builder for chaining.
     */
    public Builder setComplete(boolean value) {
      copyOnWrite();
      instance.setComplete(value);
      return this;
    }
    /**
     * <code>bool complete = 5 [json_name = "complete"];</code>
     * @return This builder for chaining.
     */
    public Builder clearComplete() {
      copyOnWrite();
      instance.clearComplete();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tandem.v1.ContactsSyncResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.ContactsSyncResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "status_",
            "contacts_",
            dev.tandem.protocol.v1.Contact.class,
            "deletedContactIds_",
            "watermarkMs_",
            "complete_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0002\u0000\u0001\f\u0002\u001b" +
              "\u0003\u021a\u0004\u0003\u0005\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.ContactsSyncResponse> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.ContactsSyncResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.ContactsSyncResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.ContactsSyncResponse)
  private static final dev.tandem.protocol.v1.ContactsSyncResponse DEFAULT_INSTANCE;
  static {
    ContactsSyncResponse defaultInstance = new ContactsSyncResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ContactsSyncResponse.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.ContactsSyncResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ContactsSyncResponse> PARSER;

  public static com.google.protobuf.Parser<ContactsSyncResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

