// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/envelope.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.Envelope)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.tandem.v1.Channel channel = 1 [json_name = "channel"];</code>
   * @return The enum numeric value on the wire for channel.
   */
  int getChannelValue();
  /**
   * <code>.tandem.v1.Channel channel = 1 [json_name = "channel"];</code>
   * @return The channel.
   */
  dev.tandem.protocol.v1.Channel getChannel();

  /**
   * <pre>
   * Per-channel, per-direction counter maintained independently by each side. The first frame a
   * side sends on a channel carries seq = 1; seq = 0 is never valid on the wire
   * (#framing-and-envelope "Envelope fields").
   * </pre>
   *
   * <code>uint64 seq = 2 [json_name = "seq"];</code>
   * @return The seq.
   */
  long getSeq();

  /**
   * <pre>
   * Highest seq received in contiguous order from the peer on this channel; 0 before anything
   * has arrived on that channel in that direction (#framing-and-envelope "Envelope fields").
   * </pre>
   *
   * <code>uint64 ack = 3 [json_name = "ack"];</code>
   * @return The ack.
   */
  long getAck();

  /**
   * <pre>
   * control.proto (E01-12) — CONTROL channel.
   * </pre>
   *
   * <code>.tandem.v1.VersionHello version_hello = 4 [json_name = "versionHello"];</code>
   * @return Whether the versionHello field is set.
   */
  boolean hasVersionHello();
  /**
   * <pre>
   * control.proto (E01-12) — CONTROL channel.
   * </pre>
   *
   * <code>.tandem.v1.VersionHello version_hello = 4 [json_name = "versionHello"];</code>
   * @return The versionHello.
   */
  dev.tandem.protocol.v1.VersionHello getVersionHello();

  /**
   * <code>.tandem.v1.Heartbeat heartbeat = 5 [json_name = "heartbeat"];</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.tandem.v1.Heartbeat heartbeat = 5 [json_name = "heartbeat"];</code>
   * @return The heartbeat.
   */
  dev.tandem.protocol.v1.Heartbeat getHeartbeat();

  /**
   * <code>.tandem.v1.CreditGrant credit_grant = 6 [json_name = "creditGrant"];</code>
   * @return Whether the creditGrant field is set.
   */
  boolean hasCreditGrant();
  /**
   * <code>.tandem.v1.CreditGrant credit_grant = 6 [json_name = "creditGrant"];</code>
   * @return The creditGrant.
   */
  dev.tandem.protocol.v1.CreditGrant getCreditGrant();

  /**
   * <code>.tandem.v1.MediaTicketGrant media_ticket_grant = 7 [json_name = "mediaTicketGrant"];</code>
   * @return Whether the mediaTicketGrant field is set.
   */
  boolean hasMediaTicketGrant();
  /**
   * <code>.tandem.v1.MediaTicketGrant media_ticket_grant = 7 [json_name = "mediaTicketGrant"];</code>
   * @return The mediaTicketGrant.
   */
  dev.tandem.protocol.v1.MediaTicketGrant getMediaTicketGrant();

  /**
   * <pre>
   * pairing.proto (E01-11) — CONTROL channel, pairing-candidate connections only.
   * </pre>
   *
   * <code>.tandem.v1.PairChallenge pair_challenge = 10 [json_name = "pairChallenge"];</code>
   * @return Whether the pairChallenge field is set.
   */
  boolean hasPairChallenge();
  /**
   * <pre>
   * pairing.proto (E01-11) — CONTROL channel, pairing-candidate connections only.
   * </pre>
   *
   * <code>.tandem.v1.PairChallenge pair_challenge = 10 [json_name = "pairChallenge"];</code>
   * @return The pairChallenge.
   */
  dev.tandem.protocol.v1.PairChallenge getPairChallenge();

  /**
   * <code>.tandem.v1.PairRequest pair_request = 11 [json_name = "pairRequest"];</code>
   * @return Whether the pairRequest field is set.
   */
  boolean hasPairRequest();
  /**
   * <code>.tandem.v1.PairRequest pair_request = 11 [json_name = "pairRequest"];</code>
   * @return The pairRequest.
   */
  dev.tandem.protocol.v1.PairRequest getPairRequest();

  /**
   * <code>.tandem.v1.PairAccepted pair_accepted = 12 [json_name = "pairAccepted"];</code>
   * @return Whether the pairAccepted field is set.
   */
  boolean hasPairAccepted();
  /**
   * <code>.tandem.v1.PairAccepted pair_accepted = 12 [json_name = "pairAccepted"];</code>
   * @return The pairAccepted.
   */
  dev.tandem.protocol.v1.PairAccepted getPairAccepted();

  /**
   * <code>.tandem.v1.PairRejected pair_rejected = 13 [json_name = "pairRejected"];</code>
   * @return Whether the pairRejected field is set.
   */
  boolean hasPairRejected();
  /**
   * <code>.tandem.v1.PairRejected pair_rejected = 13 [json_name = "pairRejected"];</code>
   * @return The pairRejected.
   */
  dev.tandem.protocol.v1.PairRejected getPairRejected();

  /**
   * <code>.tandem.v1.Revoke revoke = 14 [json_name = "revoke"];</code>
   * @return Whether the revoke field is set.
   */
  boolean hasRevoke();
  /**
   * <code>.tandem.v1.Revoke revoke = 14 [json_name = "revoke"];</code>
   * @return The revoke.
   */
  dev.tandem.protocol.v1.Revoke getRevoke();

  /**
   * <code>.tandem.v1.DeviceStatus device_status = 20 [json_name = "deviceStatus"];</code>
   * @return Whether the deviceStatus field is set.
   */
  boolean hasDeviceStatus();
  /**
   * <code>.tandem.v1.DeviceStatus device_status = 20 [json_name = "deviceStatus"];</code>
   * @return The deviceStatus.
   */
  dev.tandem.protocol.v1.DeviceStatus getDeviceStatus();

  /**
   * <code>.tandem.v1.Ring ring = 21 [json_name = "ring"];</code>
   * @return Whether the ring field is set.
   */
  boolean hasRing();
  /**
   * <code>.tandem.v1.Ring ring = 21 [json_name = "ring"];</code>
   * @return The ring.
   */
  dev.tandem.protocol.v1.Ring getRing();

  /**
   * <code>.tandem.v1.RingStop ring_stop = 22 [json_name = "ringStop"];</code>
   * @return Whether the ringStop field is set.
   */
  boolean hasRingStop();
  /**
   * <code>.tandem.v1.RingStop ring_stop = 22 [json_name = "ringStop"];</code>
   * @return The ringStop.
   */
  dev.tandem.protocol.v1.RingStop getRingStop();

  /**
   * <pre>
   * notify.proto (E30-01) — NOTIFY channel.
   * </pre>
   *
   * <code>.tandem.v1.NotificationPosted notification_posted = 30 [json_name = "notificationPosted"];</code>
   * @return Whether the notificationPosted field is set.
   */
  boolean hasNotificationPosted();
  /**
   * <pre>
   * notify.proto (E30-01) — NOTIFY channel.
   * </pre>
   *
   * <code>.tandem.v1.NotificationPosted notification_posted = 30 [json_name = "notificationPosted"];</code>
   * @return The notificationPosted.
   */
  dev.tandem.protocol.v1.NotificationPosted getNotificationPosted();

  /**
   * <code>.tandem.v1.IconData icon_data = 31 [json_name = "iconData"];</code>
   * @return Whether the iconData field is set.
   */
  boolean hasIconData();
  /**
   * <code>.tandem.v1.IconData icon_data = 31 [json_name = "iconData"];</code>
   * @return The iconData.
   */
  dev.tandem.protocol.v1.IconData getIconData();

  /**
   * <code>.tandem.v1.NotificationAction notification_action = 32 [json_name = "notificationAction"];</code>
   * @return Whether the notificationAction field is set.
   */
  boolean hasNotificationAction();
  /**
   * <code>.tandem.v1.NotificationAction notification_action = 32 [json_name = "notificationAction"];</code>
   * @return The notificationAction.
   */
  dev.tandem.protocol.v1.NotificationAction getNotificationAction();

  /**
   * <code>.tandem.v1.NotificationDismiss notification_dismiss = 33 [json_name = "notificationDismiss"];</code>
   * @return Whether the notificationDismiss field is set.
   */
  boolean hasNotificationDismiss();
  /**
   * <code>.tandem.v1.NotificationDismiss notification_dismiss = 33 [json_name = "notificationDismiss"];</code>
   * @return The notificationDismiss.
   */
  dev.tandem.protocol.v1.NotificationDismiss getNotificationDismiss();

  /**
   * <code>.tandem.v1.NotificationActionResult notification_action_result = 34 [json_name = "notificationActionResult"];</code>
   * @return Whether the notificationActionResult field is set.
   */
  boolean hasNotificationActionResult();
  /**
   * <code>.tandem.v1.NotificationActionResult notification_action_result = 34 [json_name = "notificationActionResult"];</code>
   * @return The notificationActionResult.
   */
  dev.tandem.protocol.v1.NotificationActionResult getNotificationActionResult();

  /**
   * <pre>
   * clipboard.proto (E31-01) — CLIPBOARD channel.
   * </pre>
   *
   * <code>.tandem.v1.ClipboardText clipboard_text = 40 [json_name = "clipboardText"];</code>
   * @return Whether the clipboardText field is set.
   */
  boolean hasClipboardText();
  /**
   * <pre>
   * clipboard.proto (E31-01) — CLIPBOARD channel.
   * </pre>
   *
   * <code>.tandem.v1.ClipboardText clipboard_text = 40 [json_name = "clipboardText"];</code>
   * @return The clipboardText.
   */
  dev.tandem.protocol.v1.ClipboardText getClipboardText();

  /**
   * <pre>
   * files.proto (E40-01) — FILES channel.
   * </pre>
   *
   * <code>.tandem.v1.FileOffer file_offer = 50 [json_name = "fileOffer"];</code>
   * @return Whether the fileOffer field is set.
   */
  boolean hasFileOffer();
  /**
   * <pre>
   * files.proto (E40-01) — FILES channel.
   * </pre>
   *
   * <code>.tandem.v1.FileOffer file_offer = 50 [json_name = "fileOffer"];</code>
   * @return The fileOffer.
   */
  dev.tandem.protocol.v1.FileOffer getFileOffer();

  /**
   * <code>.tandem.v1.FileAccept file_accept = 51 [json_name = "fileAccept"];</code>
   * @return Whether the fileAccept field is set.
   */
  boolean hasFileAccept();
  /**
   * <code>.tandem.v1.FileAccept file_accept = 51 [json_name = "fileAccept"];</code>
   * @return The fileAccept.
   */
  dev.tandem.protocol.v1.FileAccept getFileAccept();

  /**
   * <code>.tandem.v1.FileReject file_reject = 52 [json_name = "fileReject"];</code>
   * @return Whether the fileReject field is set.
   */
  boolean hasFileReject();
  /**
   * <code>.tandem.v1.FileReject file_reject = 52 [json_name = "fileReject"];</code>
   * @return The fileReject.
   */
  dev.tandem.protocol.v1.FileReject getFileReject();

  /**
   * <code>.tandem.v1.FileChunk file_chunk = 53 [json_name = "fileChunk"];</code>
   * @return Whether the fileChunk field is set.
   */
  boolean hasFileChunk();
  /**
   * <code>.tandem.v1.FileChunk file_chunk = 53 [json_name = "fileChunk"];</code>
   * @return The fileChunk.
   */
  dev.tandem.protocol.v1.FileChunk getFileChunk();

  /**
   * <code>.tandem.v1.FileComplete file_complete = 54 [json_name = "fileComplete"];</code>
   * @return Whether the fileComplete field is set.
   */
  boolean hasFileComplete();
  /**
   * <code>.tandem.v1.FileComplete file_complete = 54 [json_name = "fileComplete"];</code>
   * @return The fileComplete.
   */
  dev.tandem.protocol.v1.FileComplete getFileComplete();

  /**
   * <code>.tandem.v1.FileCancel file_cancel = 55 [json_name = "fileCancel"];</code>
   * @return Whether the fileCancel field is set.
   */
  boolean hasFileCancel();
  /**
   * <code>.tandem.v1.FileCancel file_cancel = 55 [json_name = "fileCancel"];</code>
   * @return The fileCancel.
   */
  dev.tandem.protocol.v1.FileCancel getFileCancel();

  /**
   * <code>.tandem.v1.FileResumeRequest file_resume_request = 56 [json_name = "fileResumeRequest"];</code>
   * @return Whether the fileResumeRequest field is set.
   */
  boolean hasFileResumeRequest();
  /**
   * <code>.tandem.v1.FileResumeRequest file_resume_request = 56 [json_name = "fileResumeRequest"];</code>
   * @return The fileResumeRequest.
   */
  dev.tandem.protocol.v1.FileResumeRequest getFileResumeRequest();

  /**
   * <pre>
   * photos.proto (E41-01) — FILES channel (no PHOTOS channel, E01-04 decision).
   * </pre>
   *
   * <code>.tandem.v1.PhotoPage photo_page = 60 [json_name = "photoPage"];</code>
   * @return Whether the photoPage field is set.
   */
  boolean hasPhotoPage();
  /**
   * <pre>
   * photos.proto (E41-01) — FILES channel (no PHOTOS channel, E01-04 decision).
   * </pre>
   *
   * <code>.tandem.v1.PhotoPage photo_page = 60 [json_name = "photoPage"];</code>
   * @return The photoPage.
   */
  dev.tandem.protocol.v1.PhotoPage getPhotoPage();

  /**
   * <code>.tandem.v1.PhotoPageResult photo_page_result = 61 [json_name = "photoPageResult"];</code>
   * @return Whether the photoPageResult field is set.
   */
  boolean hasPhotoPageResult();
  /**
   * <code>.tandem.v1.PhotoPageResult photo_page_result = 61 [json_name = "photoPageResult"];</code>
   * @return The photoPageResult.
   */
  dev.tandem.protocol.v1.PhotoPageResult getPhotoPageResult();

  /**
   * <code>.tandem.v1.ThumbRequest thumb_request = 62 [json_name = "thumbRequest"];</code>
   * @return Whether the thumbRequest field is set.
   */
  boolean hasThumbRequest();
  /**
   * <code>.tandem.v1.ThumbRequest thumb_request = 62 [json_name = "thumbRequest"];</code>
   * @return The thumbRequest.
   */
  dev.tandem.protocol.v1.ThumbRequest getThumbRequest();

  /**
   * <code>.tandem.v1.ThumbResult thumb_result = 63 [json_name = "thumbResult"];</code>
   * @return Whether the thumbResult field is set.
   */
  boolean hasThumbResult();
  /**
   * <code>.tandem.v1.ThumbResult thumb_result = 63 [json_name = "thumbResult"];</code>
   * @return The thumbResult.
   */
  dev.tandem.protocol.v1.ThumbResult getThumbResult();

  /**
   * <code>.tandem.v1.OriginalRequest original_request = 64 [json_name = "originalRequest"];</code>
   * @return Whether the originalRequest field is set.
   */
  boolean hasOriginalRequest();
  /**
   * <code>.tandem.v1.OriginalRequest original_request = 64 [json_name = "originalRequest"];</code>
   * @return The originalRequest.
   */
  dev.tandem.protocol.v1.OriginalRequest getOriginalRequest();

  /**
   * <code>.tandem.v1.PhotoError photo_error = 65 [json_name = "photoError"];</code>
   * @return Whether the photoError field is set.
   */
  boolean hasPhotoError();
  /**
   * <code>.tandem.v1.PhotoError photo_error = 65 [json_name = "photoError"];</code>
   * @return The photoError.
   */
  dev.tandem.protocol.v1.PhotoError getPhotoError();

  /**
   * <pre>
   * sms.proto (E50-01) — SMS channel.
   * </pre>
   *
   * <code>.tandem.v1.SmsSyncRequest sms_sync_request = 70 [json_name = "smsSyncRequest"];</code>
   * @return Whether the smsSyncRequest field is set.
   */
  boolean hasSmsSyncRequest();
  /**
   * <pre>
   * sms.proto (E50-01) — SMS channel.
   * </pre>
   *
   * <code>.tandem.v1.SmsSyncRequest sms_sync_request = 70 [json_name = "smsSyncRequest"];</code>
   * @return The smsSyncRequest.
   */
  dev.tandem.protocol.v1.SmsSyncRequest getSmsSyncRequest();

  /**
   * <code>.tandem.v1.SmsSyncResponse sms_sync_response = 71 [json_name = "smsSyncResponse"];</code>
   * @return Whether the smsSyncResponse field is set.
   */
  boolean hasSmsSyncResponse();
  /**
   * <code>.tandem.v1.SmsSyncResponse sms_sync_response = 71 [json_name = "smsSyncResponse"];</code>
   * @return The smsSyncResponse.
   */
  dev.tandem.protocol.v1.SmsSyncResponse getSmsSyncResponse();

  /**
   * <code>.tandem.v1.SendSmsRequest send_sms_request = 72 [json_name = "sendSmsRequest"];</code>
   * @return Whether the sendSmsRequest field is set.
   */
  boolean hasSendSmsRequest();
  /**
   * <code>.tandem.v1.SendSmsRequest send_sms_request = 72 [json_name = "sendSmsRequest"];</code>
   * @return The sendSmsRequest.
   */
  dev.tandem.protocol.v1.SendSmsRequest getSendSmsRequest();

  /**
   * <code>.tandem.v1.SendSmsStatus send_sms_status = 73 [json_name = "sendSmsStatus"];</code>
   * @return Whether the sendSmsStatus field is set.
   */
  boolean hasSendSmsStatus();
  /**
   * <code>.tandem.v1.SendSmsStatus send_sms_status = 73 [json_name = "sendSmsStatus"];</code>
   * @return The sendSmsStatus.
   */
  dev.tandem.protocol.v1.SendSmsStatus getSendSmsStatus();

  /**
   * <code>.tandem.v1.SimList sim_list = 74 [json_name = "simList"];</code>
   * @return Whether the simList field is set.
   */
  boolean hasSimList();
  /**
   * <code>.tandem.v1.SimList sim_list = 74 [json_name = "simList"];</code>
   * @return The simList.
   */
  dev.tandem.protocol.v1.SimList getSimList();

  /**
   * <pre>
   * contacts.proto (E51-01) — CONTACTS channel.
   * </pre>
   *
   * <code>.tandem.v1.ContactsSyncRequest contacts_sync_request = 80 [json_name = "contactsSyncRequest"];</code>
   * @return Whether the contactsSyncRequest field is set.
   */
  boolean hasContactsSyncRequest();
  /**
   * <pre>
   * contacts.proto (E51-01) — CONTACTS channel.
   * </pre>
   *
   * <code>.tandem.v1.ContactsSyncRequest contacts_sync_request = 80 [json_name = "contactsSyncRequest"];</code>
   * @return The contactsSyncRequest.
   */
  dev.tandem.protocol.v1.ContactsSyncRequest getContactsSyncRequest();

  /**
   * <code>.tandem.v1.ContactsSyncResponse contacts_sync_response = 81 [json_name = "contactsSyncResponse"];</code>
   * @return Whether the contactsSyncResponse field is set.
   */
  boolean hasContactsSyncResponse();
  /**
   * <code>.tandem.v1.ContactsSyncResponse contacts_sync_response = 81 [json_name = "contactsSyncResponse"];</code>
   * @return The contactsSyncResponse.
   */
  dev.tandem.protocol.v1.ContactsSyncResponse getContactsSyncResponse();

  /**
   * <pre>
   * calls.proto (E52-01) — CALLS channel.
   * </pre>
   *
   * <code>.tandem.v1.CallEvent call_event = 90 [json_name = "callEvent"];</code>
   * @return Whether the callEvent field is set.
   */
  boolean hasCallEvent();
  /**
   * <pre>
   * calls.proto (E52-01) — CALLS channel.
   * </pre>
   *
   * <code>.tandem.v1.CallEvent call_event = 90 [json_name = "callEvent"];</code>
   * @return The callEvent.
   */
  dev.tandem.protocol.v1.CallEvent getCallEvent();

  /**
   * <code>.tandem.v1.CallAction call_action = 91 [json_name = "callAction"];</code>
   * @return Whether the callAction field is set.
   */
  boolean hasCallAction();
  /**
   * <code>.tandem.v1.CallAction call_action = 91 [json_name = "callAction"];</code>
   * @return The callAction.
   */
  dev.tandem.protocol.v1.CallAction getCallAction();

  /**
   * <code>.tandem.v1.PlaceCallRequest place_call_request = 92 [json_name = "placeCallRequest"];</code>
   * @return Whether the placeCallRequest field is set.
   */
  boolean hasPlaceCallRequest();
  /**
   * <code>.tandem.v1.PlaceCallRequest place_call_request = 92 [json_name = "placeCallRequest"];</code>
   * @return The placeCallRequest.
   */
  dev.tandem.protocol.v1.PlaceCallRequest getPlaceCallRequest();

  /**
   * <code>.tandem.v1.CallActionResult call_action_result = 93 [json_name = "callActionResult"];</code>
   * @return Whether the callActionResult field is set.
   */
  boolean hasCallActionResult();
  /**
   * <code>.tandem.v1.CallActionResult call_action_result = 93 [json_name = "callActionResult"];</code>
   * @return The callActionResult.
   */
  dev.tandem.protocol.v1.CallActionResult getCallActionResult();

  public dev.tandem.protocol.v1.Envelope.PayloadCase getPayloadCase();
}
