// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/files.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface FileOfferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.FileOffer)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Raw, sender-supplied filename, untrusted peer input. Cap: &lt;= 1024 UTF-8 bytes, else the
   * receiver responds FileReject INVALID_NAME (docs/protocol/SPEC.md #files-channel "Cycle 4
   * caps", E01-22). MUST be sanitized per the E40-02 filename-sanitization rule before use as a
   * destination filename — never trusted as a path.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Raw, sender-supplied filename, untrusted peer input. Cap: &lt;= 1024 UTF-8 bytes, else the
   * receiver responds FileReject INVALID_NAME (docs/protocol/SPEC.md #files-channel "Cycle 4
   * caps", E01-22). MUST be sanitized per the E40-02 filename-sanitization rule before use as a
   * destination filename — never trusted as a path.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Whole-file size in bytes. Cap: &lt;= 64 GiB (2^36), else the receiver responds FileReject
   * TOO_LARGE (docs/protocol/SPEC.md #files-channel "Cycle 4 caps", E01-22).
   * </pre>
   *
   * <code>uint64 size = 3 [json_name = "size"];</code>
   * @return The size.
   */
  long getSize();

  /**
   * <pre>
   * Sender-supplied MIME type, untrusted peer input. Cap: &lt;= 255 bytes, else the receiver
   * responds FileReject INVALID_NAME (docs/protocol/SPEC.md #files-channel "Cycle 4 caps",
   * E01-22).
   * </pre>
   *
   * <code>string mime = 4 [json_name = "mime"];</code>
   * @return The mime.
   */
  java.lang.String getMime();
  /**
   * <pre>
   * Sender-supplied MIME type, untrusted peer input. Cap: &lt;= 255 bytes, else the receiver
   * responds FileReject INVALID_NAME (docs/protocol/SPEC.md #files-channel "Cycle 4 caps",
   * E01-22).
   * </pre>
   *
   * <code>string mime = 4 [json_name = "mime"];</code>
   * @return The bytes for mime.
   */
  com.google.protobuf.ByteString
      getMimeBytes();

  /**
   * <pre>
   * SHA-256 digest (32 bytes) of the whole source file's bytes, computed by the sender before
   * offering (docs/protocol/SPEC.md #files-channel "Handshake").
   * </pre>
   *
   * <code>bytes sha256 = 5 [json_name = "sha256"];</code>
   * @return The sha256.
   */
  com.google.protobuf.ByteString getSha256();
}
