// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/files.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface FileCompleteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.FileComplete)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
