// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/input.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface GlobalActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.GlobalAction)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.tandem.v1.GlobalActionKind action = 1 [json_name = "action"];</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.tandem.v1.GlobalActionKind action = 1 [json_name = "action"];</code>
   * @return The action.
   */
  dev.tandem.protocol.v1.GlobalActionKind getAction();
}
