// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/input.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * Protobuf enum {@code tandem.v1.GlobalActionKind}
 */
@com.google.protobuf.Generated
public enum GlobalActionKind
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>GLOBAL_ACTION_KIND_UNSPECIFIED = 0;</code>
   */
  GLOBAL_ACTION_KIND_UNSPECIFIED(0),
  /**
   * <code>GLOBAL_ACTION_KIND_BACK = 1;</code>
   */
  GLOBAL_ACTION_KIND_BACK(1),
  /**
   * <code>GLOBAL_ACTION_KIND_HOME = 2;</code>
   */
  GLOBAL_ACTION_KIND_HOME(2),
  /**
   * <code>GLOBAL_ACTION_KIND_RECENTS = 3;</code>
   */
  GLOBAL_ACTION_KIND_RECENTS(3),
  /**
   * <code>GLOBAL_ACTION_KIND_NOTIFICATIONS = 4;</code>
   */
  GLOBAL_ACTION_KIND_NOTIFICATIONS(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GLOBAL_ACTION_KIND_UNSPECIFIED = 0;</code>
   */
  public static final int GLOBAL_ACTION_KIND_UNSPECIFIED_VALUE = 0;
  /**
   * <code>GLOBAL_ACTION_KIND_BACK = 1;</code>
   */
  public static final int GLOBAL_ACTION_KIND_BACK_VALUE = 1;
  /**
   * <code>GLOBAL_ACTION_KIND_HOME = 2;</code>
   */
  public static final int GLOBAL_ACTION_KIND_HOME_VALUE = 2;
  /**
   * <code>GLOBAL_ACTION_KIND_RECENTS = 3;</code>
   */
  public static final int GLOBAL_ACTION_KIND_RECENTS_VALUE = 3;
  /**
   * <code>GLOBAL_ACTION_KIND_NOTIFICATIONS = 4;</code>
   */
  public static final int GLOBAL_ACTION_KIND_NOTIFICATIONS_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GlobalActionKind valueOf(int value) {
    return forNumber(value);
  }

  public static GlobalActionKind forNumber(int value) {
    switch (value) {
      case 0: return GLOBAL_ACTION_KIND_UNSPECIFIED;
      case 1: return GLOBAL_ACTION_KIND_BACK;
      case 2: return GLOBAL_ACTION_KIND_HOME;
      case 3: return GLOBAL_ACTION_KIND_RECENTS;
      case 4: return GLOBAL_ACTION_KIND_NOTIFICATIONS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GlobalActionKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GlobalActionKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GlobalActionKind>() {
          @java.lang.Override
          public GlobalActionKind findValueByNumber(int number) {
            return GlobalActionKind.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return GlobalActionKindVerifier.INSTANCE;
  }

  private static final class GlobalActionKindVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new GlobalActionKindVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return GlobalActionKind.forNumber(number) != null;
          }
        };

  private final int value;

  private GlobalActionKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tandem.v1.GlobalActionKind)
}

