// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/notify.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * IconData: PRD F-5.1 — an app icon, sent so the Mac can present notifications with the source
 * app's icon without asking again for every post from the same app version.
 * </pre>
 *
 * Protobuf type {@code tandem.v1.IconData}
 */
@com.google.protobuf.Generated
public  final class IconData extends
    com.google.protobuf.GeneratedMessageLite<
        IconData, IconData.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.IconData)
    IconDataOrBuilder {
  private IconData() {
    packageName_ = "";
    pngBytes_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int PACKAGE_NAME_FIELD_NUMBER = 1;
  private java.lang.String packageName_;
  /**
   * <code>string package_name = 1 [json_name = "packageName"];</code>
   * @return The packageName.
   */
  @java.lang.Override
  public java.lang.String getPackageName() {
    return packageName_;
  }
  /**
   * <code>string package_name = 1 [json_name = "packageName"];</code>
   * @return The bytes for packageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(packageName_);
  }
  /**
   * <code>string package_name = 1 [json_name = "packageName"];</code>
   * @param value The packageName to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPackageName(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    packageName_ = value;
  }
  /**
   * <code>string package_name = 1 [json_name = "packageName"];</code>
   */
  private void clearPackageName() {

    packageName_ = getDefaultInstance().getPackageName();
  }
  /**
   * <code>string package_name = 1 [json_name = "packageName"];</code>
   * @param value The bytes for packageName to set.
   */
  private void setPackageNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    packageName_ = value.toStringUtf8();

  }

  public static final int VERSION_CODE_FIELD_NUMBER = 2;
  private long versionCode_;
  /**
   * <code>int64 version_code = 2 [json_name = "versionCode"];</code>
   * @return The versionCode.
   */
  @java.lang.Override
  public long getVersionCode() {
    return versionCode_;
  }
  /**
   * <code>int64 version_code = 2 [json_name = "versionCode"];</code>
   * @param value The versionCode to set.
   */
  private void setVersionCode(long value) {
    
    versionCode_ = value;
  }
  /**
   * <code>int64 version_code = 2 [json_name = "versionCode"];</code>
   */
  private void clearVersionCode() {

    versionCode_ = 0L;
  }

  public static final int PNG_BYTES_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString pngBytes_;
  /**
   * <pre>
   * Cap: &lt;= 64 KiB and &lt;= 256x256 px (E01-22); over-cap data is discarded and a placeholder icon
   * used instead (E30-05) rather than rejected at the protocol layer.
   * </pre>
   *
   * <code>bytes png_bytes = 3 [json_name = "pngBytes"];</code>
   * @return The pngBytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPngBytes() {
    return pngBytes_;
  }
  /**
   * <pre>
   * Cap: &lt;= 64 KiB and &lt;= 256x256 px (E01-22); over-cap data is discarded and a placeholder icon
   * used instead (E30-05) rather than rejected at the protocol layer.
   * </pre>
   *
   * <code>bytes png_bytes = 3 [json_name = "pngBytes"];</code>
   * @param value The pngBytes to set.
   */
  private void setPngBytes(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    pngBytes_ = value;
  }
  /**
   * <pre>
   * Cap: &lt;= 64 KiB and &lt;= 256x256 px (E01-22); over-cap data is discarded and a placeholder icon
   * used instead (E30-05) rather than rejected at the protocol layer.
   * </pre>
   *
   * <code>bytes png_bytes = 3 [json_name = "pngBytes"];</code>
   */
  private void clearPngBytes() {

    pngBytes_ = getDefaultInstance().getPngBytes();
  }

  public static dev.tandem.protocol.v1.IconData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.IconData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.IconData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.IconData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.IconData prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * IconData: PRD F-5.1 — an app icon, sent so the Mac can present notifications with the source
   * app's icon without asking again for every post from the same app version.
   * </pre>
   *
   * Protobuf type {@code tandem.v1.IconData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.IconData, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.IconData)
      dev.tandem.protocol.v1.IconDataOrBuilder {
    // Construct using dev.tandem.protocol.v1.IconData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string package_name = 1 [json_name = "packageName"];</code>
     * @return The packageName.
     */
    @java.lang.Override
    public java.lang.String getPackageName() {
      return instance.getPackageName();
    }
    /**
     * <code>string package_name = 1 [json_name = "packageName"];</code>
     * @return The bytes for packageName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      return instance.getPackageNameBytes();
    }
    /**
     * <code>string package_name = 1 [json_name = "packageName"];</code>
     * @param value The packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageName(
        java.lang.String value) {
      copyOnWrite();
      instance.setPackageName(value);
      return this;
    }
    /**
     * <code>string package_name = 1 [json_name = "packageName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageName() {
      copyOnWrite();
      instance.clearPackageName();
      return this;
    }
    /**
     * <code>string package_name = 1 [json_name = "packageName"];</code>
     * @param value The bytes for packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPackageNameBytes(value);
      return this;
    }

    /**
     * <code>int64 version_code = 2 [json_name = "versionCode"];</code>
     * @return The versionCode.
     */
    @java.lang.Override
    public long getVersionCode() {
      return instance.getVersionCode();
    }
    /**
     * <code>int64 version_code = 2 [json_name = "versionCode"];</code>
     * @param value The versionCode to set.
     * @return This builder for chaining.
     */
    public Builder setVersionCode(long value) {
      copyOnWrite();
      instance.setVersionCode(value);
      return this;
    }
    /**
     * <code>int64 version_code = 2 [json_name = "versionCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersionCode() {
      copyOnWrite();
      instance.clearVersionCode();
      return this;
    }

    /**
     * <pre>
     * Cap: &lt;= 64 KiB and &lt;= 256x256 px (E01-22); over-cap data is discarded and a placeholder icon
     * used instead (E30-05) rather than rejected at the protocol layer.
     * </pre>
     *
     * <code>bytes png_bytes = 3 [json_name = "pngBytes"];</code>
     * @return The pngBytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPngBytes() {
      return instance.getPngBytes();
    }
    /**
     * <pre>
     * Cap: &lt;= 64 KiB and &lt;= 256x256 px (E01-22); over-cap data is discarded and a placeholder icon
     * used instead (E30-05) rather than rejected at the protocol layer.
     * </pre>
     *
     * <code>bytes png_bytes = 3 [json_name = "pngBytes"];</code>
     * @param value The pngBytes to set.
     * @return This builder for chaining.
     */
    public Builder setPngBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPngBytes(value);
      return this;
    }
    /**
     * <pre>
     * Cap: &lt;= 64 KiB and &lt;= 256x256 px (E01-22); over-cap data is discarded and a placeholder icon
     * used instead (E30-05) rather than rejected at the protocol layer.
     * </pre>
     *
     * <code>bytes png_bytes = 3 [json_name = "pngBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPngBytes() {
      copyOnWrite();
      instance.clearPngBytes();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tandem.v1.IconData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.IconData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "packageName_",
            "versionCode_",
            "pngBytes_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0002" +
              "\u0003\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.IconData> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.IconData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.IconData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.IconData)
  private static final dev.tandem.protocol.v1.IconData DEFAULT_INSTANCE;
  static {
    IconData defaultInstance = new IconData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      IconData.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.IconData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<IconData> PARSER;

  public static com.google.protobuf.Parser<IconData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

