// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/input.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * ImeEnter: the IME enter/action key.
 * </pre>
 *
 * Protobuf type {@code tandem.v1.ImeEnter}
 */
@com.google.protobuf.Generated
public  final class ImeEnter extends
    com.google.protobuf.GeneratedMessageLite<
        ImeEnter, ImeEnter.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.ImeEnter)
    ImeEnterOrBuilder {
  private ImeEnter() {
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.ImeEnter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.ImeEnter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.ImeEnter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.ImeEnter prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ImeEnter: the IME enter/action key.
   * </pre>
   *
   * Protobuf type {@code tandem.v1.ImeEnter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.ImeEnter, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.ImeEnter)
      dev.tandem.protocol.v1.ImeEnterOrBuilder {
    // Construct using dev.tandem.protocol.v1.ImeEnter.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    // @@protoc_insertion_point(builder_scope:tandem.v1.ImeEnter)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.ImeEnter();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = null;
          java.lang.String info =
              "\u0000\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.ImeEnter> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.ImeEnter.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.ImeEnter>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.ImeEnter)
  private static final dev.tandem.protocol.v1.ImeEnter DEFAULT_INSTANCE;
  static {
    ImeEnter defaultInstance = new ImeEnter();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ImeEnter.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.ImeEnter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ImeEnter> PARSER;

  public static com.google.protobuf.Parser<ImeEnter> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

