// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/input.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * InputEvent: one remote input action. `session_id` is the 16-byte id of the active mirror session
 * this event is bound to; the receiver MUST drop the event when it is absent, not exactly 16 bytes,
 * or not the active session's id (stale or foreign). Exactly one `event` variant is set; an unset
 * oneof is rejected UNKNOWN_PAYLOAD_TYPE.
 * </pre>
 *
 * Protobuf type {@code tandem.v1.InputEvent}
 */
@com.google.protobuf.Generated
public  final class InputEvent extends
    com.google.protobuf.GeneratedMessageLite<
        InputEvent, InputEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.InputEvent)
    InputEventOrBuilder {
  private InputEvent() {
    sessionId_ = com.google.protobuf.ByteString.EMPTY;
  }
  private int eventCase_ = 0;
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.AbstractMessageLite.InternalOneOfEnum {
    TAP(2),
    SWIPE(3),
    SCROLL(4),
    GLOBAL_ACTION(5),
    SET_TEXT(6),
    TEXT_EDIT(7),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 2: return TAP;
        case 3: return SWIPE;
        case 4: return SCROLL;
        case 5: return GLOBAL_ACTION;
        case 6: return SET_TEXT;
        case 7: return TEXT_EDIT;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    @java.lang.Override public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  private void clearEvent() {
    eventCase_ = 0;
    event_ = null;
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString sessionId_;
  /**
   * <code>bytes session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSessionId() {
    return sessionId_;
  }
  /**
   * <code>bytes session_id = 1 [json_name = "sessionId"];</code>
   * @param value The sessionId to set.
   */
  private void setSessionId(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sessionId_ = value;
  }
  /**
   * <code>bytes session_id = 1 [json_name = "sessionId"];</code>
   */
  private void clearSessionId() {

    sessionId_ = getDefaultInstance().getSessionId();
  }

  public static final int TAP_FIELD_NUMBER = 2;
  /**
   * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
   */
  @java.lang.Override
  public boolean hasTap() {
    return eventCase_ == 2;
  }
  /**
   * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.Tap getTap() {
    if (eventCase_ == 2) {
       return (dev.tandem.protocol.v1.Tap) event_;
    }
    return dev.tandem.protocol.v1.Tap.getDefaultInstance();
  }
  /**
   * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTap(dev.tandem.protocol.v1.Tap value) {
    value.getClass();  // minimal bytecode null check
    event_ = value;
    eventCase_ = 2;
  }
  /**
   * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeTap(dev.tandem.protocol.v1.Tap value) {
    value.getClass();  // minimal bytecode null check
    if (eventCase_ == 2 &&
        event_ != dev.tandem.protocol.v1.Tap.getDefaultInstance()) {
      event_ = dev.tandem.protocol.v1.Tap.newBuilder((dev.tandem.protocol.v1.Tap) event_)
          .mergeFrom(value).buildPartial();
    } else {
      event_ = value;
    }
    eventCase_ = 2;
  }
  /**
   * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
   */
  private void clearTap() {
    if (eventCase_ == 2) {
      eventCase_ = 0;
      event_ = null;
    }
  }

  public static final int SWIPE_FIELD_NUMBER = 3;
  /**
   * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
   */
  @java.lang.Override
  public boolean hasSwipe() {
    return eventCase_ == 3;
  }
  /**
   * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.Swipe getSwipe() {
    if (eventCase_ == 3) {
       return (dev.tandem.protocol.v1.Swipe) event_;
    }
    return dev.tandem.protocol.v1.Swipe.getDefaultInstance();
  }
  /**
   * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSwipe(dev.tandem.protocol.v1.Swipe value) {
    value.getClass();  // minimal bytecode null check
    event_ = value;
    eventCase_ = 3;
  }
  /**
   * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeSwipe(dev.tandem.protocol.v1.Swipe value) {
    value.getClass();  // minimal bytecode null check
    if (eventCase_ == 3 &&
        event_ != dev.tandem.protocol.v1.Swipe.getDefaultInstance()) {
      event_ = dev.tandem.protocol.v1.Swipe.newBuilder((dev.tandem.protocol.v1.Swipe) event_)
          .mergeFrom(value).buildPartial();
    } else {
      event_ = value;
    }
    eventCase_ = 3;
  }
  /**
   * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
   */
  private void clearSwipe() {
    if (eventCase_ == 3) {
      eventCase_ = 0;
      event_ = null;
    }
  }

  public static final int SCROLL_FIELD_NUMBER = 4;
  /**
   * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
   */
  @java.lang.Override
  public boolean hasScroll() {
    return eventCase_ == 4;
  }
  /**
   * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.Scroll getScroll() {
    if (eventCase_ == 4) {
       return (dev.tandem.protocol.v1.Scroll) event_;
    }
    return dev.tandem.protocol.v1.Scroll.getDefaultInstance();
  }
  /**
   * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setScroll(dev.tandem.protocol.v1.Scroll value) {
    value.getClass();  // minimal bytecode null check
    event_ = value;
    eventCase_ = 4;
  }
  /**
   * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeScroll(dev.tandem.protocol.v1.Scroll value) {
    value.getClass();  // minimal bytecode null check
    if (eventCase_ == 4 &&
        event_ != dev.tandem.protocol.v1.Scroll.getDefaultInstance()) {
      event_ = dev.tandem.protocol.v1.Scroll.newBuilder((dev.tandem.protocol.v1.Scroll) event_)
          .mergeFrom(value).buildPartial();
    } else {
      event_ = value;
    }
    eventCase_ = 4;
  }
  /**
   * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
   */
  private void clearScroll() {
    if (eventCase_ == 4) {
      eventCase_ = 0;
      event_ = null;
    }
  }

  public static final int GLOBAL_ACTION_FIELD_NUMBER = 5;
  /**
   * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
   */
  @java.lang.Override
  public boolean hasGlobalAction() {
    return eventCase_ == 5;
  }
  /**
   * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.GlobalAction getGlobalAction() {
    if (eventCase_ == 5) {
       return (dev.tandem.protocol.v1.GlobalAction) event_;
    }
    return dev.tandem.protocol.v1.GlobalAction.getDefaultInstance();
  }
  /**
   * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setGlobalAction(dev.tandem.protocol.v1.GlobalAction value) {
    value.getClass();  // minimal bytecode null check
    event_ = value;
    eventCase_ = 5;
  }
  /**
   * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeGlobalAction(dev.tandem.protocol.v1.GlobalAction value) {
    value.getClass();  // minimal bytecode null check
    if (eventCase_ == 5 &&
        event_ != dev.tandem.protocol.v1.GlobalAction.getDefaultInstance()) {
      event_ = dev.tandem.protocol.v1.GlobalAction.newBuilder((dev.tandem.protocol.v1.GlobalAction) event_)
          .mergeFrom(value).buildPartial();
    } else {
      event_ = value;
    }
    eventCase_ = 5;
  }
  /**
   * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
   */
  private void clearGlobalAction() {
    if (eventCase_ == 5) {
      eventCase_ = 0;
      event_ = null;
    }
  }

  public static final int SET_TEXT_FIELD_NUMBER = 6;
  /**
   * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
   */
  @java.lang.Override
  public boolean hasSetText() {
    return eventCase_ == 6;
  }
  /**
   * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.SetText getSetText() {
    if (eventCase_ == 6) {
       return (dev.tandem.protocol.v1.SetText) event_;
    }
    return dev.tandem.protocol.v1.SetText.getDefaultInstance();
  }
  /**
   * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSetText(dev.tandem.protocol.v1.SetText value) {
    value.getClass();  // minimal bytecode null check
    event_ = value;
    eventCase_ = 6;
  }
  /**
   * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeSetText(dev.tandem.protocol.v1.SetText value) {
    value.getClass();  // minimal bytecode null check
    if (eventCase_ == 6 &&
        event_ != dev.tandem.protocol.v1.SetText.getDefaultInstance()) {
      event_ = dev.tandem.protocol.v1.SetText.newBuilder((dev.tandem.protocol.v1.SetText) event_)
          .mergeFrom(value).buildPartial();
    } else {
      event_ = value;
    }
    eventCase_ = 6;
  }
  /**
   * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
   */
  private void clearSetText() {
    if (eventCase_ == 6) {
      eventCase_ = 0;
      event_ = null;
    }
  }

  public static final int TEXT_EDIT_FIELD_NUMBER = 7;
  /**
   * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
   */
  @java.lang.Override
  public boolean hasTextEdit() {
    return eventCase_ == 7;
  }
  /**
   * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.TextEdit getTextEdit() {
    if (eventCase_ == 7) {
       return (dev.tandem.protocol.v1.TextEdit) event_;
    }
    return dev.tandem.protocol.v1.TextEdit.getDefaultInstance();
  }
  /**
   * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTextEdit(dev.tandem.protocol.v1.TextEdit value) {
    value.getClass();  // minimal bytecode null check
    event_ = value;
    eventCase_ = 7;
  }
  /**
   * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeTextEdit(dev.tandem.protocol.v1.TextEdit value) {
    value.getClass();  // minimal bytecode null check
    if (eventCase_ == 7 &&
        event_ != dev.tandem.protocol.v1.TextEdit.getDefaultInstance()) {
      event_ = dev.tandem.protocol.v1.TextEdit.newBuilder((dev.tandem.protocol.v1.TextEdit) event_)
          .mergeFrom(value).buildPartial();
    } else {
      event_ = value;
    }
    eventCase_ = 7;
  }
  /**
   * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
   */
  private void clearTextEdit() {
    if (eventCase_ == 7) {
      eventCase_ = 0;
      event_ = null;
    }
  }

  public static dev.tandem.protocol.v1.InputEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.InputEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.InputEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.InputEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.InputEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * InputEvent: one remote input action. `session_id` is the 16-byte id of the active mirror session
   * this event is bound to; the receiver MUST drop the event when it is absent, not exactly 16 bytes,
   * or not the active session's id (stale or foreign). Exactly one `event` variant is set; an unset
   * oneof is rejected UNKNOWN_PAYLOAD_TYPE.
   * </pre>
   *
   * Protobuf type {@code tandem.v1.InputEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.InputEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.InputEvent)
      dev.tandem.protocol.v1.InputEventOrBuilder {
    // Construct using dev.tandem.protocol.v1.InputEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public EventCase
        getEventCase() {
      return instance.getEventCase();
    }

    public Builder clearEvent() {
      copyOnWrite();
      instance.clearEvent();
      return this;
    }


    /**
     * <code>bytes session_id = 1 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSessionId() {
      return instance.getSessionId();
    }
    /**
     * <code>bytes session_id = 1 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSessionId(value);
      return this;
    }
    /**
     * <code>bytes session_id = 1 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      copyOnWrite();
      instance.clearSessionId();
      return this;
    }

    /**
     * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
     */
    @java.lang.Override
    public boolean hasTap() {
      return instance.hasTap();
    }
    /**
     * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.Tap getTap() {
      return instance.getTap();
    }
    /**
     * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
     */
    public Builder setTap(dev.tandem.protocol.v1.Tap value) {
      copyOnWrite();
      instance.setTap(value);
      return this;
    }
    /**
     * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
     */
    public Builder setTap(
        dev.tandem.protocol.v1.Tap.Builder builderForValue) {
      copyOnWrite();
      instance.setTap(builderForValue.build());
      return this;
    }
    /**
     * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
     */
    public Builder mergeTap(dev.tandem.protocol.v1.Tap value) {
      copyOnWrite();
      instance.mergeTap(value);
      return this;
    }
    /**
     * <code>.tandem.v1.Tap tap = 2 [json_name = "tap"];</code>
     */
    public Builder clearTap() {
      copyOnWrite();
      instance.clearTap();
      return this;
    }

    /**
     * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
     */
    @java.lang.Override
    public boolean hasSwipe() {
      return instance.hasSwipe();
    }
    /**
     * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.Swipe getSwipe() {
      return instance.getSwipe();
    }
    /**
     * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
     */
    public Builder setSwipe(dev.tandem.protocol.v1.Swipe value) {
      copyOnWrite();
      instance.setSwipe(value);
      return this;
    }
    /**
     * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
     */
    public Builder setSwipe(
        dev.tandem.protocol.v1.Swipe.Builder builderForValue) {
      copyOnWrite();
      instance.setSwipe(builderForValue.build());
      return this;
    }
    /**
     * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
     */
    public Builder mergeSwipe(dev.tandem.protocol.v1.Swipe value) {
      copyOnWrite();
      instance.mergeSwipe(value);
      return this;
    }
    /**
     * <code>.tandem.v1.Swipe swipe = 3 [json_name = "swipe"];</code>
     */
    public Builder clearSwipe() {
      copyOnWrite();
      instance.clearSwipe();
      return this;
    }

    /**
     * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
     */
    @java.lang.Override
    public boolean hasScroll() {
      return instance.hasScroll();
    }
    /**
     * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.Scroll getScroll() {
      return instance.getScroll();
    }
    /**
     * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
     */
    public Builder setScroll(dev.tandem.protocol.v1.Scroll value) {
      copyOnWrite();
      instance.setScroll(value);
      return this;
    }
    /**
     * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
     */
    public Builder setScroll(
        dev.tandem.protocol.v1.Scroll.Builder builderForValue) {
      copyOnWrite();
      instance.setScroll(builderForValue.build());
      return this;
    }
    /**
     * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
     */
    public Builder mergeScroll(dev.tandem.protocol.v1.Scroll value) {
      copyOnWrite();
      instance.mergeScroll(value);
      return this;
    }
    /**
     * <code>.tandem.v1.Scroll scroll = 4 [json_name = "scroll"];</code>
     */
    public Builder clearScroll() {
      copyOnWrite();
      instance.clearScroll();
      return this;
    }

    /**
     * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
     */
    @java.lang.Override
    public boolean hasGlobalAction() {
      return instance.hasGlobalAction();
    }
    /**
     * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.GlobalAction getGlobalAction() {
      return instance.getGlobalAction();
    }
    /**
     * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
     */
    public Builder setGlobalAction(dev.tandem.protocol.v1.GlobalAction value) {
      copyOnWrite();
      instance.setGlobalAction(value);
      return this;
    }
    /**
     * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
     */
    public Builder setGlobalAction(
        dev.tandem.protocol.v1.GlobalAction.Builder builderForValue) {
      copyOnWrite();
      instance.setGlobalAction(builderForValue.build());
      return this;
    }
    /**
     * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
     */
    public Builder mergeGlobalAction(dev.tandem.protocol.v1.GlobalAction value) {
      copyOnWrite();
      instance.mergeGlobalAction(value);
      return this;
    }
    /**
     * <code>.tandem.v1.GlobalAction global_action = 5 [json_name = "globalAction"];</code>
     */
    public Builder clearGlobalAction() {
      copyOnWrite();
      instance.clearGlobalAction();
      return this;
    }

    /**
     * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
     */
    @java.lang.Override
    public boolean hasSetText() {
      return instance.hasSetText();
    }
    /**
     * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.SetText getSetText() {
      return instance.getSetText();
    }
    /**
     * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
     */
    public Builder setSetText(dev.tandem.protocol.v1.SetText value) {
      copyOnWrite();
      instance.setSetText(value);
      return this;
    }
    /**
     * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
     */
    public Builder setSetText(
        dev.tandem.protocol.v1.SetText.Builder builderForValue) {
      copyOnWrite();
      instance.setSetText(builderForValue.build());
      return this;
    }
    /**
     * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
     */
    public Builder mergeSetText(dev.tandem.protocol.v1.SetText value) {
      copyOnWrite();
      instance.mergeSetText(value);
      return this;
    }
    /**
     * <code>.tandem.v1.SetText set_text = 6 [json_name = "setText"];</code>
     */
    public Builder clearSetText() {
      copyOnWrite();
      instance.clearSetText();
      return this;
    }

    /**
     * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
     */
    @java.lang.Override
    public boolean hasTextEdit() {
      return instance.hasTextEdit();
    }
    /**
     * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.TextEdit getTextEdit() {
      return instance.getTextEdit();
    }
    /**
     * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
     */
    public Builder setTextEdit(dev.tandem.protocol.v1.TextEdit value) {
      copyOnWrite();
      instance.setTextEdit(value);
      return this;
    }
    /**
     * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
     */
    public Builder setTextEdit(
        dev.tandem.protocol.v1.TextEdit.Builder builderForValue) {
      copyOnWrite();
      instance.setTextEdit(builderForValue.build());
      return this;
    }
    /**
     * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
     */
    public Builder mergeTextEdit(dev.tandem.protocol.v1.TextEdit value) {
      copyOnWrite();
      instance.mergeTextEdit(value);
      return this;
    }
    /**
     * <code>.tandem.v1.TextEdit text_edit = 7 [json_name = "textEdit"];</code>
     */
    public Builder clearTextEdit() {
      copyOnWrite();
      instance.clearTextEdit();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tandem.v1.InputEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.InputEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "event_",
            "eventCase_",
            "sessionId_",
            dev.tandem.protocol.v1.Tap.class,
            dev.tandem.protocol.v1.Swipe.class,
            dev.tandem.protocol.v1.Scroll.class,
            dev.tandem.protocol.v1.GlobalAction.class,
            dev.tandem.protocol.v1.SetText.class,
            dev.tandem.protocol.v1.TextEdit.class,
          };
          java.lang.String info =
              "\u0000\u0007\u0001\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\n\u0002<\u0000" +
              "\u0003<\u0000\u0004<\u0000\u0005<\u0000\u0006<\u0000\u0007<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.InputEvent> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.InputEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.InputEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.InputEvent)
  private static final dev.tandem.protocol.v1.InputEvent DEFAULT_INSTANCE;
  static {
    InputEvent defaultInstance = new InputEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InputEvent.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.InputEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InputEvent> PARSER;

  public static com.google.protobuf.Parser<InputEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

