// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/manual_pairing.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * ManualPairResult: SPEC #manual-pairing step 6. Sent by the Mac only after the owner clicked Pair;
 * `accepted` is always true on the wire and any other value is rejected PAIRING_FAILED (a decline is
 * PairRejected, not this message).
 * </pre>
 *
 * Protobuf type {@code tandem.v1.ManualPairResult}
 */
@com.google.protobuf.Generated
public  final class ManualPairResult extends
    com.google.protobuf.GeneratedMessageLite<
        ManualPairResult, ManualPairResult.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.ManualPairResult)
    ManualPairResultOrBuilder {
  private ManualPairResult() {
  }
  public static final int ACCEPTED_FIELD_NUMBER = 1;
  private boolean accepted_;
  /**
   * <code>bool accepted = 1 [json_name = "accepted"];</code>
   * @return The accepted.
   */
  @java.lang.Override
  public boolean getAccepted() {
    return accepted_;
  }
  /**
   * <code>bool accepted = 1 [json_name = "accepted"];</code>
   * @param value The accepted to set.
   */
  private void setAccepted(boolean value) {
    
    accepted_ = value;
  }
  /**
   * <code>bool accepted = 1 [json_name = "accepted"];</code>
   */
  private void clearAccepted() {

    accepted_ = false;
  }

  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.ManualPairResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.ManualPairResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.ManualPairResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.ManualPairResult prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * ManualPairResult: SPEC #manual-pairing step 6. Sent by the Mac only after the owner clicked Pair;
   * `accepted` is always true on the wire and any other value is rejected PAIRING_FAILED (a decline is
   * PairRejected, not this message).
   * </pre>
   *
   * Protobuf type {@code tandem.v1.ManualPairResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.ManualPairResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.ManualPairResult)
      dev.tandem.protocol.v1.ManualPairResultOrBuilder {
    // Construct using dev.tandem.protocol.v1.ManualPairResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool accepted = 1 [json_name = "accepted"];</code>
     * @return The accepted.
     */
    @java.lang.Override
    public boolean getAccepted() {
      return instance.getAccepted();
    }
    /**
     * <code>bool accepted = 1 [json_name = "accepted"];</code>
     * @param value The accepted to set.
     * @return This builder for chaining.
     */
    public Builder setAccepted(boolean value) {
      copyOnWrite();
      instance.setAccepted(value);
      return this;
    }
    /**
     * <code>bool accepted = 1 [json_name = "accepted"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAccepted() {
      copyOnWrite();
      instance.clearAccepted();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tandem.v1.ManualPairResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.ManualPairResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "accepted_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.ManualPairResult> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.ManualPairResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.ManualPairResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.ManualPairResult)
  private static final dev.tandem.protocol.v1.ManualPairResult DEFAULT_INSTANCE;
  static {
    ManualPairResult defaultInstance = new ManualPairResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ManualPairResult.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.ManualPairResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ManualPairResult> PARSER;

  public static com.google.protobuf.Parser<ManualPairResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

