// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/media.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface MediaMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.MediaMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.tandem.v1.MediaFormat media_format = 1 [json_name = "mediaFormat"];</code>
   * @return Whether the mediaFormat field is set.
   */
  boolean hasMediaFormat();
  /**
   * <code>.tandem.v1.MediaFormat media_format = 1 [json_name = "mediaFormat"];</code>
   * @return The mediaFormat.
   */
  dev.tandem.protocol.v1.MediaFormat getMediaFormat();

  /**
   * <code>.tandem.v1.MediaFrame media_frame = 2 [json_name = "mediaFrame"];</code>
   * @return Whether the mediaFrame field is set.
   */
  boolean hasMediaFrame();
  /**
   * <code>.tandem.v1.MediaFrame media_frame = 2 [json_name = "mediaFrame"];</code>
   * @return The mediaFrame.
   */
  dev.tandem.protocol.v1.MediaFrame getMediaFrame();

  /**
   * <code>.tandem.v1.KeyframeRequest keyframe_request = 3 [json_name = "keyframeRequest"];</code>
   * @return Whether the keyframeRequest field is set.
   */
  boolean hasKeyframeRequest();
  /**
   * <code>.tandem.v1.KeyframeRequest keyframe_request = 3 [json_name = "keyframeRequest"];</code>
   * @return The keyframeRequest.
   */
  dev.tandem.protocol.v1.KeyframeRequest getKeyframeRequest();

  /**
   * <code>.tandem.v1.RotationChanged rotation_changed = 4 [json_name = "rotationChanged"];</code>
   * @return Whether the rotationChanged field is set.
   */
  boolean hasRotationChanged();
  /**
   * <code>.tandem.v1.RotationChanged rotation_changed = 4 [json_name = "rotationChanged"];</code>
   * @return The rotationChanged.
   */
  dev.tandem.protocol.v1.RotationChanged getRotationChanged();

  public dev.tandem.protocol.v1.MediaMessage.PayloadCase getPayloadCase();
}
