// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/media.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface MediaHelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.MediaHello)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Exactly 32 bytes (256 bits) as issued in MediaTicketGrant.ticket.
   * </pre>
   *
   * <code>bytes ticket = 1 [json_name = "ticket"];</code>
   * @return The ticket.
   */
  com.google.protobuf.ByteString getTicket();

  /**
   * <pre>
   * Exactly 16 bytes from a CSPRNG, minted by the phone when the user starts the mirror session
   * (Q19, D-77). The Mac echoes it in every input message of the session.
   * </pre>
   *
   * <code>bytes mirror_session_id = 2 [json_name = "mirrorSessionId"];</code>
   * @return The mirrorSessionId.
   */
  com.google.protobuf.ByteString getMirrorSessionId();
}
