// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/media.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * Protobuf enum {@code tandem.v1.MediaCodec}
 */
@com.google.protobuf.Generated
public enum MediaCodec
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>MEDIA_CODEC_UNSPECIFIED = 0;</code>
   */
  MEDIA_CODEC_UNSPECIFIED(0),
  /**
   * <code>MEDIA_CODEC_H264 = 1;</code>
   */
  MEDIA_CODEC_H264(1),
  /**
   * <code>MEDIA_CODEC_HEVC = 2;</code>
   */
  MEDIA_CODEC_HEVC(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MEDIA_CODEC_UNSPECIFIED = 0;</code>
   */
  public static final int MEDIA_CODEC_UNSPECIFIED_VALUE = 0;
  /**
   * <code>MEDIA_CODEC_H264 = 1;</code>
   */
  public static final int MEDIA_CODEC_H264_VALUE = 1;
  /**
   * <code>MEDIA_CODEC_HEVC = 2;</code>
   */
  public static final int MEDIA_CODEC_HEVC_VALUE = 2;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MediaCodec valueOf(int value) {
    return forNumber(value);
  }

  public static MediaCodec forNumber(int value) {
    switch (value) {
      case 0: return MEDIA_CODEC_UNSPECIFIED;
      case 1: return MEDIA_CODEC_H264;
      case 2: return MEDIA_CODEC_HEVC;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MediaCodec>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MediaCodec> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MediaCodec>() {
          @java.lang.Override
          public MediaCodec findValueByNumber(int number) {
            return MediaCodec.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return MediaCodecVerifier.INSTANCE;
  }

  private static final class MediaCodecVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new MediaCodecVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return MediaCodec.forNumber(number) != null;
          }
        };

  private final int value;

  private MediaCodec(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tandem.v1.MediaCodec)
}

