// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/notify.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * NotificationAction: PRD F-5.2 — the Mac sends this when the user taps an action (or submits a
 * reply) on a mirrored notification.
 * </pre>
 *
 * Protobuf type {@code tandem.v1.NotificationAction}
 */
@com.google.protobuf.Generated
public  final class NotificationAction extends
    com.google.protobuf.GeneratedMessageLite<
        NotificationAction, NotificationAction.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.NotificationAction)
    NotificationActionOrBuilder {
  private NotificationAction() {
    key_ = "";
    replyText_ = "";
  }
  public static final int KEY_FIELD_NUMBER = 1;
  private java.lang.String key_;
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    return key_;
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(key_);
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @param value The key to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setKey(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    key_ = value;
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   */
  private void clearKey() {

    key_ = getDefaultInstance().getKey();
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @param value The bytes for key to set.
   */
  private void setKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    key_ = value.toStringUtf8();

  }

  public static final int ACTION_INDEX_FIELD_NUMBER = 2;
  private int actionIndex_;
  /**
   * <pre>
   * Index into the source notification's action list, in the order NotificationPosted's source
   * notification declared them.
   * </pre>
   *
   * <code>int32 action_index = 2 [json_name = "actionIndex"];</code>
   * @return The actionIndex.
   */
  @java.lang.Override
  public int getActionIndex() {
    return actionIndex_;
  }
  /**
   * <pre>
   * Index into the source notification's action list, in the order NotificationPosted's source
   * notification declared them.
   * </pre>
   *
   * <code>int32 action_index = 2 [json_name = "actionIndex"];</code>
   * @param value The actionIndex to set.
   */
  private void setActionIndex(int value) {
    
    actionIndex_ = value;
  }
  /**
   * <pre>
   * Index into the source notification's action list, in the order NotificationPosted's source
   * notification declared them.
   * </pre>
   *
   * <code>int32 action_index = 2 [json_name = "actionIndex"];</code>
   */
  private void clearActionIndex() {

    actionIndex_ = 0;
  }

  public static final int REPLY_TEXT_FIELD_NUMBER = 3;
  private java.lang.String replyText_;
  /**
   * <pre>
   * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
   * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
   * the user (e.g. in a sent-reply confirmation).
   * </pre>
   *
   * <code>string reply_text = 3 [json_name = "replyText"];</code>
   * @return The replyText.
   */
  @java.lang.Override
  public java.lang.String getReplyText() {
    return replyText_;
  }
  /**
   * <pre>
   * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
   * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
   * the user (e.g. in a sent-reply confirmation).
   * </pre>
   *
   * <code>string reply_text = 3 [json_name = "replyText"];</code>
   * @return The bytes for replyText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReplyTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(replyText_);
  }
  /**
   * <pre>
   * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
   * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
   * the user (e.g. in a sent-reply confirmation).
   * </pre>
   *
   * <code>string reply_text = 3 [json_name = "replyText"];</code>
   * @param value The replyText to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setReplyText(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    replyText_ = value;
  }
  /**
   * <pre>
   * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
   * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
   * the user (e.g. in a sent-reply confirmation).
   * </pre>
   *
   * <code>string reply_text = 3 [json_name = "replyText"];</code>
   */
  private void clearReplyText() {

    replyText_ = getDefaultInstance().getReplyText();
  }
  /**
   * <pre>
   * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
   * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
   * the user (e.g. in a sent-reply confirmation).
   * </pre>
   *
   * <code>string reply_text = 3 [json_name = "replyText"];</code>
   * @param value The bytes for replyText to set.
   */
  private void setReplyTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    replyText_ = value.toStringUtf8();

  }

  public static dev.tandem.protocol.v1.NotificationAction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.NotificationAction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.NotificationAction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.NotificationAction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.NotificationAction prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * NotificationAction: PRD F-5.2 — the Mac sends this when the user taps an action (or submits a
   * reply) on a mirrored notification.
   * </pre>
   *
   * Protobuf type {@code tandem.v1.NotificationAction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.NotificationAction, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.NotificationAction)
      dev.tandem.protocol.v1.NotificationActionOrBuilder {
    // Construct using dev.tandem.protocol.v1.NotificationAction.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return instance.getKey();
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return instance.getKeyBytes();
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setKey(value);
      return this;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      copyOnWrite();
      instance.clearKey();
      return this;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyBytes(value);
      return this;
    }

    /**
     * <pre>
     * Index into the source notification's action list, in the order NotificationPosted's source
     * notification declared them.
     * </pre>
     *
     * <code>int32 action_index = 2 [json_name = "actionIndex"];</code>
     * @return The actionIndex.
     */
    @java.lang.Override
    public int getActionIndex() {
      return instance.getActionIndex();
    }
    /**
     * <pre>
     * Index into the source notification's action list, in the order NotificationPosted's source
     * notification declared them.
     * </pre>
     *
     * <code>int32 action_index = 2 [json_name = "actionIndex"];</code>
     * @param value The actionIndex to set.
     * @return This builder for chaining.
     */
    public Builder setActionIndex(int value) {
      copyOnWrite();
      instance.setActionIndex(value);
      return this;
    }
    /**
     * <pre>
     * Index into the source notification's action list, in the order NotificationPosted's source
     * notification declared them.
     * </pre>
     *
     * <code>int32 action_index = 2 [json_name = "actionIndex"];</code>
     * @return This builder for chaining.
     */
    public Builder clearActionIndex() {
      copyOnWrite();
      instance.clearActionIndex();
      return this;
    }

    /**
     * <pre>
     * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
     * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
     * the user (e.g. in a sent-reply confirmation).
     * </pre>
     *
     * <code>string reply_text = 3 [json_name = "replyText"];</code>
     * @return The replyText.
     */
    @java.lang.Override
    public java.lang.String getReplyText() {
      return instance.getReplyText();
    }
    /**
     * <pre>
     * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
     * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
     * the user (e.g. in a sent-reply confirmation).
     * </pre>
     *
     * <code>string reply_text = 3 [json_name = "replyText"];</code>
     * @return The bytes for replyText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReplyTextBytes() {
      return instance.getReplyTextBytes();
    }
    /**
     * <pre>
     * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
     * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
     * the user (e.g. in a sent-reply confirmation).
     * </pre>
     *
     * <code>string reply_text = 3 [json_name = "replyText"];</code>
     * @param value The replyText to set.
     * @return This builder for chaining.
     */
    public Builder setReplyText(
        java.lang.String value) {
      copyOnWrite();
      instance.setReplyText(value);
      return this;
    }
    /**
     * <pre>
     * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
     * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
     * the user (e.g. in a sent-reply confirmation).
     * </pre>
     *
     * <code>string reply_text = 3 [json_name = "replyText"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyText() {
      copyOnWrite();
      instance.clearReplyText();
      return this;
    }
    /**
     * <pre>
     * Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
     * &lt;= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
     * the user (e.g. in a sent-reply confirmation).
     * </pre>
     *
     * <code>string reply_text = 3 [json_name = "replyText"];</code>
     * @param value The bytes for replyText to set.
     * @return This builder for chaining.
     */
    public Builder setReplyTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReplyTextBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tandem.v1.NotificationAction)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.NotificationAction();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "key_",
            "actionIndex_",
            "replyText_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.NotificationAction> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.NotificationAction.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.NotificationAction>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.NotificationAction)
  private static final dev.tandem.protocol.v1.NotificationAction DEFAULT_INSTANCE;
  static {
    NotificationAction defaultInstance = new NotificationAction();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NotificationAction.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.NotificationAction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NotificationAction> PARSER;

  public static com.google.protobuf.Parser<NotificationAction> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

