// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/notify.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface NotificationActionResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.NotificationActionResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
   * @return The status.
   */
  dev.tandem.protocol.v1.NotificationActionResult.Status getStatus();
}
