// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/notify.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * NotificationActionResult: PRD F-5.2 — the phone answers every received NotificationAction with
 * this, so the Mac can report a reply/action as sent, or "no longer available" if the source
 * notification was already gone (UC-09 alternate).
 * </pre>
 *
 * Protobuf type {@code tandem.v1.NotificationActionResult}
 */
@com.google.protobuf.Generated
public  final class NotificationActionResult extends
    com.google.protobuf.GeneratedMessageLite<
        NotificationActionResult, NotificationActionResult.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.NotificationActionResult)
    NotificationActionResultOrBuilder {
  private NotificationActionResult() {
    key_ = "";
  }
  /**
   * Protobuf enum {@code tandem.v1.NotificationActionResult.Status}
   */
  public enum Status
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>STATUS_UNSPECIFIED = 0;</code>
     */
    STATUS_UNSPECIFIED(0),
    /**
     * <code>STATUS_OK = 1;</code>
     */
    STATUS_OK(1),
    /**
     * <code>STATUS_GONE = 2;</code>
     */
    STATUS_GONE(2),
    /**
     * <code>STATUS_FAILED = 3;</code>
     */
    STATUS_FAILED(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATUS_UNSPECIFIED = 0;</code>
     */
    public static final int STATUS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>STATUS_OK = 1;</code>
     */
    public static final int STATUS_OK_VALUE = 1;
    /**
     * <code>STATUS_GONE = 2;</code>
     */
    public static final int STATUS_GONE_VALUE = 2;
    /**
     * <code>STATUS_FAILED = 3;</code>
     */
    public static final int STATUS_FAILED_VALUE = 3;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return STATUS_UNSPECIFIED;
        case 1: return STATUS_OK;
        case 2: return STATUS_GONE;
        case 3: return STATUS_FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            @java.lang.Override
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return StatusVerifier.INSTANCE;
    }

    private static final class StatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier
                INSTANCE = new StatusVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return Status.forNumber(number) != null;
            }
          };

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tandem.v1.NotificationActionResult.Status)
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private java.lang.String key_;
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    return key_;
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(key_);
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @param value The key to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setKey(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    key_ = value;
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   */
  private void clearKey() {

    key_ = getDefaultInstance().getKey();
  }
  /**
   * <code>string key = 1 [json_name = "key"];</code>
   * @param value The bytes for key to set.
   */
  private void setKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    key_ = value.toStringUtf8();

  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.NotificationActionResult.Status getStatus() {
    dev.tandem.protocol.v1.NotificationActionResult.Status result = dev.tandem.protocol.v1.NotificationActionResult.Status.forNumber(status_);
    return result == null ? dev.tandem.protocol.v1.NotificationActionResult.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
   * @param value The enum numeric value on the wire for status to set.
   */
  private void setStatusValue(int value) {
      status_ = value;
  }
  /**
   * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
   * @param value The status to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setStatus(dev.tandem.protocol.v1.NotificationActionResult.Status value) {
    status_ = value.getNumber();

  }
  /**
   * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
   */
  private void clearStatus() {

    status_ = 0;
  }

  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.NotificationActionResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.NotificationActionResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.NotificationActionResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.NotificationActionResult prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * NotificationActionResult: PRD F-5.2 — the phone answers every received NotificationAction with
   * this, so the Mac can report a reply/action as sent, or "no longer available" if the source
   * notification was already gone (UC-09 alternate).
   * </pre>
   *
   * Protobuf type {@code tandem.v1.NotificationActionResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.NotificationActionResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.NotificationActionResult)
      dev.tandem.protocol.v1.NotificationActionResultOrBuilder {
    // Construct using dev.tandem.protocol.v1.NotificationActionResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return instance.getKey();
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return instance.getKeyBytes();
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setKey(value);
      return this;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      copyOnWrite();
      instance.clearKey();
      return this;
    }
    /**
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyBytes(value);
      return this;
    }

    /**
     * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return instance.getStatusValue();
    }
    /**
     * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
     * @param value The status to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      copyOnWrite();
      instance.setStatusValue(value);
      return this;
    }
    /**
     * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.NotificationActionResult.Status getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(dev.tandem.protocol.v1.NotificationActionResult.Status value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tandem.v1.NotificationActionResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.NotificationActionResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "key_",
            "status_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\f" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.NotificationActionResult> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.NotificationActionResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.NotificationActionResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.NotificationActionResult)
  private static final dev.tandem.protocol.v1.NotificationActionResult DEFAULT_INSTANCE;
  static {
    NotificationActionResult defaultInstance = new NotificationActionResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NotificationActionResult.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.NotificationActionResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NotificationActionResult> PARSER;

  public static com.google.protobuf.Parser<NotificationActionResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

