// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/media_control.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * NowPlaying: phone -&gt; Mac. Sent when the active media session or its metadata changes. title,
 * artist and album are untrusted peer input (SPEC.md #untrusted-strings sanitization applies before
 * rendering); the sender truncates them to the caps below, the receiver rejects longer values.
 * </pre>
 *
 * Protobuf type {@code tandem.v1.NowPlaying}
 */
@com.google.protobuf.Generated
public  final class NowPlaying extends
    com.google.protobuf.GeneratedMessageLite<
        NowPlaying, NowPlaying.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.NowPlaying)
    NowPlayingOrBuilder {
  private NowPlaying() {
    title_ = "";
    artist_ = "";
    album_ = "";
  }
  private int bitField0_;
  public static final int TITLE_FIELD_NUMBER = 1;
  private java.lang.String title_;
  /**
   * <pre>
   * &lt;= 256 chars
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <pre>
   * &lt;= 256 chars
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <pre>
   * &lt;= 256 chars
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   * @param value The title to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTitle(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    title_ = value;
  }
  /**
   * <pre>
   * &lt;= 256 chars
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   */
  private void clearTitle() {

    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <pre>
   * &lt;= 256 chars
   * </pre>
   *
   * <code>string title = 1 [json_name = "title"];</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();

  }

  public static final int ARTIST_FIELD_NUMBER = 2;
  private java.lang.String artist_;
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>string artist = 2 [json_name = "artist"];</code>
   * @return The artist.
   */
  @java.lang.Override
  public java.lang.String getArtist() {
    return artist_;
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>string artist = 2 [json_name = "artist"];</code>
   * @return The bytes for artist.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArtistBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(artist_);
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>string artist = 2 [json_name = "artist"];</code>
   * @param value The artist to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setArtist(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    artist_ = value;
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>string artist = 2 [json_name = "artist"];</code>
   */
  private void clearArtist() {

    artist_ = getDefaultInstance().getArtist();
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>string artist = 2 [json_name = "artist"];</code>
   * @param value The bytes for artist to set.
   */
  private void setArtistBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    artist_ = value.toStringUtf8();

  }

  public static final int STATE_FIELD_NUMBER = 3;
  private int state_;
  /**
   * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override
  public int getStateValue() {
    return state_;
  }
  /**
   * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
   * @return The state.
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.PlaybackState getState() {
    dev.tandem.protocol.v1.PlaybackState result = dev.tandem.protocol.v1.PlaybackState.forNumber(state_);
    return result == null ? dev.tandem.protocol.v1.PlaybackState.UNRECOGNIZED : result;
  }
  /**
   * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
   * @param value The enum numeric value on the wire for state to set.
   */
  private void setStateValue(int value) {
      state_ = value;
  }
  /**
   * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
   * @param value The state to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setState(dev.tandem.protocol.v1.PlaybackState value) {
    state_ = value.getNumber();

  }
  /**
   * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
   */
  private void clearState() {

    state_ = 0;
  }

  public static final int ALBUM_FIELD_NUMBER = 4;
  private java.lang.String album_;
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>optional string album = 4 [json_name = "album"];</code>
   * @return Whether the album field is set.
   */
  @java.lang.Override
  public boolean hasAlbum() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>optional string album = 4 [json_name = "album"];</code>
   * @return The album.
   */
  @java.lang.Override
  public java.lang.String getAlbum() {
    return album_;
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>optional string album = 4 [json_name = "album"];</code>
   * @return The bytes for album.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlbumBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(album_);
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>optional string album = 4 [json_name = "album"];</code>
   * @param value The album to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAlbum(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    bitField0_ |= 0x00000001;
    album_ = value;
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>optional string album = 4 [json_name = "album"];</code>
   */
  private void clearAlbum() {
    bitField0_ = (bitField0_ & ~0x00000001);
    album_ = getDefaultInstance().getAlbum();
  }
  /**
   * <pre>
   * &lt;= 128 chars
   * </pre>
   *
   * <code>optional string album = 4 [json_name = "album"];</code>
   * @param value The bytes for album to set.
   */
  private void setAlbumBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    album_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int DURATION_MS_FIELD_NUMBER = 5;
  private long durationMs_;
  /**
   * <code>optional int64 duration_ms = 5 [json_name = "durationMs"];</code>
   * @return Whether the durationMs field is set.
   */
  @java.lang.Override
  public boolean hasDurationMs() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 duration_ms = 5 [json_name = "durationMs"];</code>
   * @return The durationMs.
   */
  @java.lang.Override
  public long getDurationMs() {
    return durationMs_;
  }
  /**
   * <code>optional int64 duration_ms = 5 [json_name = "durationMs"];</code>
   * @param value The durationMs to set.
   */
  private void setDurationMs(long value) {
    bitField0_ |= 0x00000002;
    durationMs_ = value;
  }
  /**
   * <code>optional int64 duration_ms = 5 [json_name = "durationMs"];</code>
   */
  private void clearDurationMs() {
    bitField0_ = (bitField0_ & ~0x00000002);
    durationMs_ = 0L;
  }

  public static dev.tandem.protocol.v1.NowPlaying parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.NowPlaying parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.NowPlaying parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.NowPlaying parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.NowPlaying prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * NowPlaying: phone -&gt; Mac. Sent when the active media session or its metadata changes. title,
   * artist and album are untrusted peer input (SPEC.md #untrusted-strings sanitization applies before
   * rendering); the sender truncates them to the caps below, the receiver rejects longer values.
   * </pre>
   *
   * Protobuf type {@code tandem.v1.NowPlaying}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.NowPlaying, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.NowPlaying)
      dev.tandem.protocol.v1.NowPlayingOrBuilder {
    // Construct using dev.tandem.protocol.v1.NowPlaying.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * &lt;= 256 chars
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <pre>
     * &lt;= 256 chars
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <pre>
     * &lt;= 256 chars
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <pre>
     * &lt;= 256 chars
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <pre>
     * &lt;= 256 chars
     * </pre>
     *
     * <code>string title = 1 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>string artist = 2 [json_name = "artist"];</code>
     * @return The artist.
     */
    @java.lang.Override
    public java.lang.String getArtist() {
      return instance.getArtist();
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>string artist = 2 [json_name = "artist"];</code>
     * @return The bytes for artist.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getArtistBytes() {
      return instance.getArtistBytes();
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>string artist = 2 [json_name = "artist"];</code>
     * @param value The artist to set.
     * @return This builder for chaining.
     */
    public Builder setArtist(
        java.lang.String value) {
      copyOnWrite();
      instance.setArtist(value);
      return this;
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>string artist = 2 [json_name = "artist"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArtist() {
      copyOnWrite();
      instance.clearArtist();
      return this;
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>string artist = 2 [json_name = "artist"];</code>
     * @param value The bytes for artist to set.
     * @return This builder for chaining.
     */
    public Builder setArtistBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setArtistBytes(value);
      return this;
    }

    /**
     * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override
    public int getStateValue() {
      return instance.getStateValue();
    }
    /**
     * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
     * @param value The state to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      copyOnWrite();
      instance.setStateValue(value);
      return this;
    }
    /**
     * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
     * @return The state.
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.PlaybackState getState() {
      return instance.getState();
    }
    /**
     * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setState(dev.tandem.protocol.v1.PlaybackState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <code>.tandem.v1.PlaybackState state = 3 [json_name = "state"];</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }

    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>optional string album = 4 [json_name = "album"];</code>
     * @return Whether the album field is set.
     */
    @java.lang.Override
    public boolean hasAlbum() {
      return instance.hasAlbum();
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>optional string album = 4 [json_name = "album"];</code>
     * @return The album.
     */
    @java.lang.Override
    public java.lang.String getAlbum() {
      return instance.getAlbum();
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>optional string album = 4 [json_name = "album"];</code>
     * @return The bytes for album.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      return instance.getAlbumBytes();
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>optional string album = 4 [json_name = "album"];</code>
     * @param value The album to set.
     * @return This builder for chaining.
     */
    public Builder setAlbum(
        java.lang.String value) {
      copyOnWrite();
      instance.setAlbum(value);
      return this;
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>optional string album = 4 [json_name = "album"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlbum() {
      copyOnWrite();
      instance.clearAlbum();
      return this;
    }
    /**
     * <pre>
     * &lt;= 128 chars
     * </pre>
     *
     * <code>optional string album = 4 [json_name = "album"];</code>
     * @param value The bytes for album to set.
     * @return This builder for chaining.
     */
    public Builder setAlbumBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAlbumBytes(value);
      return this;
    }

    /**
     * <code>optional int64 duration_ms = 5 [json_name = "durationMs"];</code>
     * @return Whether the durationMs field is set.
     */
    @java.lang.Override
    public boolean hasDurationMs() {
      return instance.hasDurationMs();
    }
    /**
     * <code>optional int64 duration_ms = 5 [json_name = "durationMs"];</code>
     * @return The durationMs.
     */
    @java.lang.Override
    public long getDurationMs() {
      return instance.getDurationMs();
    }
    /**
     * <code>optional int64 duration_ms = 5 [json_name = "durationMs"];</code>
     * @param value The durationMs to set.
     * @return This builder for chaining.
     */
    public Builder setDurationMs(long value) {
      copyOnWrite();
      instance.setDurationMs(value);
      return this;
    }
    /**
     * <code>optional int64 duration_ms = 5 [json_name = "durationMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationMs() {
      copyOnWrite();
      instance.clearDurationMs();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tandem.v1.NowPlaying)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.NowPlaying();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "title_",
            "artist_",
            "state_",
            "album_",
            "durationMs_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\f\u0004\u1208\u0000\u0005\u1002\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.NowPlaying> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.NowPlaying.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.NowPlaying>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.NowPlaying)
  private static final dev.tandem.protocol.v1.NowPlaying DEFAULT_INSTANCE;
  static {
    NowPlaying defaultInstance = new NowPlaying();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NowPlaying.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.NowPlaying getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NowPlaying> PARSER;

  public static com.google.protobuf.Parser<NowPlaying> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

