// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/photos.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface OriginalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.OriginalRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string transfer_id = 2 [json_name = "transferId"];</code>
   * @return The transferId.
   */
  java.lang.String getTransferId();
  /**
   * <code>string transfer_id = 2 [json_name = "transferId"];</code>
   * @return The bytes for transferId.
   */
  com.google.protobuf.ByteString
      getTransferIdBytes();
}
