// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/pairing.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface PairRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.PairRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.tandem.v1.DeviceInfo device_info = 1 [json_name = "deviceInfo"];</code>
   * @return Whether the deviceInfo field is set.
   */
  boolean hasDeviceInfo();
  /**
   * <code>.tandem.v1.DeviceInfo device_info = 1 [json_name = "deviceInfo"];</code>
   * @return The deviceInfo.
   */
  dev.tandem.protocol.v1.DeviceInfo getDeviceInfo();

  /**
   * <pre>
   * HMAC-SHA256(secret, transcript) per #pairing "Proof computation"; the Mac recomputes and
   * compares this in constant time (invariant 6).
   * </pre>
   *
   * <code>bytes proof = 2 [json_name = "proof"];</code>
   * @return The proof.
   */
  com.google.protobuf.ByteString getProof();
}
