// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/pairing.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * PairRejectedReason: the wire-collapsed reason carried by PairRejected
 * (docs/planning/decisions.md D-72, cycle 4 oracle collapse). No wire value distinguishes a bad
 * proof from an expired window from a malformed request (D-17); the E01-05 local reasons
 * (EXPIRED, BAD_PROOF, MALFORMED) never appear on the wire, and local reason TIMEOUT sends no
 * PairRejected at all (D-72).
 * </pre>
 *
 * Protobuf enum {@code tandem.v1.PairRejectedReason}
 */
@com.google.protobuf.Generated
public enum PairRejectedReason
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * Never legal on the wire; fatal for a receiver, like any other proto3 zero-value default
   * relied on as a real signal.
   * </pre>
   *
   * <code>PAIR_REJECTED_REASON_UNSPECIFIED = 0;</code>
   */
  PAIR_REJECTED_REASON_UNSPECIFIED(0),
  /**
   * <pre>
   * The owner explicitly declined (clicked Don't Pair, pressed Escape, or closed the dialog).
   * </pre>
   *
   * <code>PAIR_REJECTED_REASON_REJECTED_BY_OWNER = 1;</code>
   */
  PAIR_REJECTED_REASON_REJECTED_BY_OWNER(1),
  /**
   * <pre>
   * Every other local rejection reason a connection can actually receive: EXPIRED, BAD_PROOF, or
   * MALFORMED.
   * </pre>
   *
   * <code>PAIR_REJECTED_REASON_PAIRING_UNAVAILABLE = 2;</code>
   */
  PAIR_REJECTED_REASON_PAIRING_UNAVAILABLE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Never legal on the wire; fatal for a receiver, like any other proto3 zero-value default
   * relied on as a real signal.
   * </pre>
   *
   * <code>PAIR_REJECTED_REASON_UNSPECIFIED = 0;</code>
   */
  public static final int PAIR_REJECTED_REASON_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * The owner explicitly declined (clicked Don't Pair, pressed Escape, or closed the dialog).
   * </pre>
   *
   * <code>PAIR_REJECTED_REASON_REJECTED_BY_OWNER = 1;</code>
   */
  public static final int PAIR_REJECTED_REASON_REJECTED_BY_OWNER_VALUE = 1;
  /**
   * <pre>
   * Every other local rejection reason a connection can actually receive: EXPIRED, BAD_PROOF, or
   * MALFORMED.
   * </pre>
   *
   * <code>PAIR_REJECTED_REASON_PAIRING_UNAVAILABLE = 2;</code>
   */
  public static final int PAIR_REJECTED_REASON_PAIRING_UNAVAILABLE_VALUE = 2;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PairRejectedReason valueOf(int value) {
    return forNumber(value);
  }

  public static PairRejectedReason forNumber(int value) {
    switch (value) {
      case 0: return PAIR_REJECTED_REASON_UNSPECIFIED;
      case 1: return PAIR_REJECTED_REASON_REJECTED_BY_OWNER;
      case 2: return PAIR_REJECTED_REASON_PAIRING_UNAVAILABLE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PairRejectedReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PairRejectedReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PairRejectedReason>() {
          @java.lang.Override
          public PairRejectedReason findValueByNumber(int number) {
            return PairRejectedReason.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return PairRejectedReasonVerifier.INSTANCE;
  }

  private static final class PairRejectedReasonVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new PairRejectedReasonVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return PairRejectedReason.forNumber(number) != null;
          }
        };

  private final int value;

  private PairRejectedReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tandem.v1.PairRejectedReason)
}

