// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/photos.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface PhotoErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.PhotoError)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.tandem.v1.PhotoErrorKind kind = 1 [json_name = "kind"];</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.tandem.v1.PhotoErrorKind kind = 1 [json_name = "kind"];</code>
   * @return The kind.
   */
  dev.tandem.protocol.v1.PhotoErrorKind getKind();

  /**
   * <code>string ref = 2 [json_name = "ref"];</code>
   * @return The ref.
   */
  java.lang.String getRef();
  /**
   * <code>string ref = 2 [json_name = "ref"];</code>
   * @return The bytes for ref.
   */
  com.google.protobuf.ByteString
      getRefBytes();

  /**
   * <code>.tandem.v1.PhotoErrorReason reason = 3 [json_name = "reason"];</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.tandem.v1.PhotoErrorReason reason = 3 [json_name = "reason"];</code>
   * @return The reason.
   */
  dev.tandem.protocol.v1.PhotoErrorReason getReason();
}
