// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/photos.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface PhotoPageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.PhotoPage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string cursor = 1 [json_name = "cursor"];</code>
   * @return The cursor.
   */
  java.lang.String getCursor();
  /**
   * <code>string cursor = 1 [json_name = "cursor"];</code>
   * @return The bytes for cursor.
   */
  com.google.protobuf.ByteString
      getCursorBytes();

  /**
   * <code>uint32 limit = 2 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();
}
