// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/photos.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * PhotoErrorReason: why the request named by PhotoError.kind/ref failed. BUSY is a Cycle 4
 * addition (E01-22): the receiver already has more than 8 outstanding ThumbRequests, or more
 * than 1 outstanding PhotoPage, from this peer (docs/protocol/SPEC.md #files-channel "Photos
 * Cycle 4 caps").
 * </pre>
 *
 * Protobuf enum {@code tandem.v1.PhotoErrorReason}
 */
@com.google.protobuf.Generated
public enum PhotoErrorReason
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>PHOTO_ERROR_REASON_UNSPECIFIED = 0;</code>
   */
  PHOTO_ERROR_REASON_UNSPECIFIED(0),
  /**
   * <code>PHOTO_ERROR_REASON_NOT_FOUND = 1;</code>
   */
  PHOTO_ERROR_REASON_NOT_FOUND(1),
  /**
   * <code>PHOTO_ERROR_REASON_ACCESS_DENIED = 2;</code>
   */
  PHOTO_ERROR_REASON_ACCESS_DENIED(2),
  /**
   * <code>PHOTO_ERROR_REASON_INVALID_CURSOR = 3;</code>
   */
  PHOTO_ERROR_REASON_INVALID_CURSOR(3),
  /**
   * <code>PHOTO_ERROR_REASON_BUSY = 4;</code>
   */
  PHOTO_ERROR_REASON_BUSY(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PHOTO_ERROR_REASON_UNSPECIFIED = 0;</code>
   */
  public static final int PHOTO_ERROR_REASON_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PHOTO_ERROR_REASON_NOT_FOUND = 1;</code>
   */
  public static final int PHOTO_ERROR_REASON_NOT_FOUND_VALUE = 1;
  /**
   * <code>PHOTO_ERROR_REASON_ACCESS_DENIED = 2;</code>
   */
  public static final int PHOTO_ERROR_REASON_ACCESS_DENIED_VALUE = 2;
  /**
   * <code>PHOTO_ERROR_REASON_INVALID_CURSOR = 3;</code>
   */
  public static final int PHOTO_ERROR_REASON_INVALID_CURSOR_VALUE = 3;
  /**
   * <code>PHOTO_ERROR_REASON_BUSY = 4;</code>
   */
  public static final int PHOTO_ERROR_REASON_BUSY_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PhotoErrorReason valueOf(int value) {
    return forNumber(value);
  }

  public static PhotoErrorReason forNumber(int value) {
    switch (value) {
      case 0: return PHOTO_ERROR_REASON_UNSPECIFIED;
      case 1: return PHOTO_ERROR_REASON_NOT_FOUND;
      case 2: return PHOTO_ERROR_REASON_ACCESS_DENIED;
      case 3: return PHOTO_ERROR_REASON_INVALID_CURSOR;
      case 4: return PHOTO_ERROR_REASON_BUSY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PhotoErrorReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PhotoErrorReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PhotoErrorReason>() {
          @java.lang.Override
          public PhotoErrorReason findValueByNumber(int number) {
            return PhotoErrorReason.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return PhotoErrorReasonVerifier.INSTANCE;
  }

  private static final class PhotoErrorReasonVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new PhotoErrorReasonVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return PhotoErrorReason.forNumber(number) != null;
          }
        };

  private final int value;

  private PhotoErrorReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tandem.v1.PhotoErrorReason)
}

