// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/input.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

@com.google.protobuf.Generated
public interface ScrollOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tandem.v1.Scroll)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 x = 1 [json_name = "x"];</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>uint32 y = 2 [json_name = "y"];</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>sint32 dx = 3 [json_name = "dx"];</code>
   * @return The dx.
   */
  int getDx();

  /**
   * <code>sint32 dy = 4 [json_name = "dy"];</code>
   * @return The dy.
   */
  int getDy();
}
