// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/sms.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * SendSmsErrorCode: SendSmsStatus.error_code, set only when state = FAILED. TOO_LONG (body over
 * 1600 characters) and RATE_LIMITED (more than 10 sends per 60 s) are rejected before
 * SmsManager is called (docs/protocol/SPEC.md #sms-channel "Send").
 * </pre>
 *
 * Protobuf enum {@code tandem.v1.SendSmsErrorCode}
 */
@com.google.protobuf.Generated
public enum SendSmsErrorCode
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>SEND_SMS_ERROR_CODE_UNSPECIFIED = 0;</code>
   */
  SEND_SMS_ERROR_CODE_UNSPECIFIED(0),
  /**
   * <code>SEND_SMS_ERROR_CODE_GENERIC_FAILURE = 1;</code>
   */
  SEND_SMS_ERROR_CODE_GENERIC_FAILURE(1),
  /**
   * <code>SEND_SMS_ERROR_CODE_NO_SERVICE = 2;</code>
   */
  SEND_SMS_ERROR_CODE_NO_SERVICE(2),
  /**
   * <code>SEND_SMS_ERROR_CODE_RADIO_OFF = 3;</code>
   */
  SEND_SMS_ERROR_CODE_RADIO_OFF(3),
  /**
   * <code>SEND_SMS_ERROR_CODE_PERMISSION_REQUIRED = 4;</code>
   */
  SEND_SMS_ERROR_CODE_PERMISSION_REQUIRED(4),
  /**
   * <code>SEND_SMS_ERROR_CODE_INVALID_ADDRESS = 5;</code>
   */
  SEND_SMS_ERROR_CODE_INVALID_ADDRESS(5),
  /**
   * <code>SEND_SMS_ERROR_CODE_TOO_LONG = 6;</code>
   */
  SEND_SMS_ERROR_CODE_TOO_LONG(6),
  /**
   * <code>SEND_SMS_ERROR_CODE_RATE_LIMITED = 7;</code>
   */
  SEND_SMS_ERROR_CODE_RATE_LIMITED(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SEND_SMS_ERROR_CODE_UNSPECIFIED = 0;</code>
   */
  public static final int SEND_SMS_ERROR_CODE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>SEND_SMS_ERROR_CODE_GENERIC_FAILURE = 1;</code>
   */
  public static final int SEND_SMS_ERROR_CODE_GENERIC_FAILURE_VALUE = 1;
  /**
   * <code>SEND_SMS_ERROR_CODE_NO_SERVICE = 2;</code>
   */
  public static final int SEND_SMS_ERROR_CODE_NO_SERVICE_VALUE = 2;
  /**
   * <code>SEND_SMS_ERROR_CODE_RADIO_OFF = 3;</code>
   */
  public static final int SEND_SMS_ERROR_CODE_RADIO_OFF_VALUE = 3;
  /**
   * <code>SEND_SMS_ERROR_CODE_PERMISSION_REQUIRED = 4;</code>
   */
  public static final int SEND_SMS_ERROR_CODE_PERMISSION_REQUIRED_VALUE = 4;
  /**
   * <code>SEND_SMS_ERROR_CODE_INVALID_ADDRESS = 5;</code>
   */
  public static final int SEND_SMS_ERROR_CODE_INVALID_ADDRESS_VALUE = 5;
  /**
   * <code>SEND_SMS_ERROR_CODE_TOO_LONG = 6;</code>
   */
  public static final int SEND_SMS_ERROR_CODE_TOO_LONG_VALUE = 6;
  /**
   * <code>SEND_SMS_ERROR_CODE_RATE_LIMITED = 7;</code>
   */
  public static final int SEND_SMS_ERROR_CODE_RATE_LIMITED_VALUE = 7;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SendSmsErrorCode valueOf(int value) {
    return forNumber(value);
  }

  public static SendSmsErrorCode forNumber(int value) {
    switch (value) {
      case 0: return SEND_SMS_ERROR_CODE_UNSPECIFIED;
      case 1: return SEND_SMS_ERROR_CODE_GENERIC_FAILURE;
      case 2: return SEND_SMS_ERROR_CODE_NO_SERVICE;
      case 3: return SEND_SMS_ERROR_CODE_RADIO_OFF;
      case 4: return SEND_SMS_ERROR_CODE_PERMISSION_REQUIRED;
      case 5: return SEND_SMS_ERROR_CODE_INVALID_ADDRESS;
      case 6: return SEND_SMS_ERROR_CODE_TOO_LONG;
      case 7: return SEND_SMS_ERROR_CODE_RATE_LIMITED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SendSmsErrorCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SendSmsErrorCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SendSmsErrorCode>() {
          @java.lang.Override
          public SendSmsErrorCode findValueByNumber(int number) {
            return SendSmsErrorCode.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return SendSmsErrorCodeVerifier.INSTANCE;
  }

  private static final class SendSmsErrorCodeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new SendSmsErrorCodeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return SendSmsErrorCode.forNumber(number) != null;
          }
        };

  private final int value;

  private SendSmsErrorCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tandem.v1.SendSmsErrorCode)
}

