// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/sms.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * SmsSyncResponse: phone -&gt; Mac, one page of a sync.
 * </pre>
 *
 * Protobuf type {@code tandem.v1.SmsSyncResponse}
 */
@com.google.protobuf.Generated
public  final class SmsSyncResponse extends
    com.google.protobuf.GeneratedMessageLite<
        SmsSyncResponse, SmsSyncResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:tandem.v1.SmsSyncResponse)
    SmsSyncResponseOrBuilder {
  private SmsSyncResponse() {
    threads_ = emptyProtobufList();
    messages_ = emptyProtobufList();
  }
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.SmsSyncStatus getStatus() {
    dev.tandem.protocol.v1.SmsSyncStatus result = dev.tandem.protocol.v1.SmsSyncStatus.forNumber(status_);
    return result == null ? dev.tandem.protocol.v1.SmsSyncStatus.UNRECOGNIZED : result;
  }
  /**
   * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
   * @param value The enum numeric value on the wire for status to set.
   */
  private void setStatusValue(int value) {
      status_ = value;
  }
  /**
   * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
   * @param value The status to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setStatus(dev.tandem.protocol.v1.SmsSyncStatus value) {
    status_ = value.getNumber();

  }
  /**
   * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
   */
  private void clearStatus() {

    status_ = 0;
  }

  public static final int THREADS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<dev.tandem.protocol.v1.SmsThread> threads_;
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  @java.lang.Override
  public java.util.List<dev.tandem.protocol.v1.SmsThread> getThreadsList() {
    return threads_;
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  public java.util.List<? extends dev.tandem.protocol.v1.SmsThreadOrBuilder> 
      getThreadsOrBuilderList() {
    return threads_;
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  @java.lang.Override
  public int getThreadsCount() {
    return threads_.size();
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.SmsThread getThreads(int index) {
    return threads_.get(index);
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  public dev.tandem.protocol.v1.SmsThreadOrBuilder getThreadsOrBuilder(
      int index) {
    return threads_.get(index);
  }
  private void ensureThreadsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.tandem.protocol.v1.SmsThread> tmp = threads_;
    if (!tmp.isModifiable()) {
      threads_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setThreads(
      int index, dev.tandem.protocol.v1.SmsThread value) {
    value.getClass();  // minimal bytecode null check
    ensureThreadsIsMutable();
    threads_.set(index, value);
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addThreads(dev.tandem.protocol.v1.SmsThread value) {
    value.getClass();  // minimal bytecode null check
    ensureThreadsIsMutable();
    threads_.add(value);
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addThreads(
      int index, dev.tandem.protocol.v1.SmsThread value) {
    value.getClass();  // minimal bytecode null check
    ensureThreadsIsMutable();
    threads_.add(index, value);
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  private void addAllThreads(
      java.lang.Iterable<? extends dev.tandem.protocol.v1.SmsThread> values) {
    ensureThreadsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, threads_);
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  private void clearThreads() {
    threads_ = emptyProtobufList();
  }
  /**
   * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
   */
  private void removeThreads(int index) {
    ensureThreadsIsMutable();
    threads_.remove(index);
  }

  public static final int MESSAGES_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<dev.tandem.protocol.v1.SmsMessage> messages_;
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  @java.lang.Override
  public java.util.List<dev.tandem.protocol.v1.SmsMessage> getMessagesList() {
    return messages_;
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  public java.util.List<? extends dev.tandem.protocol.v1.SmsMessageOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  @java.lang.Override
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  @java.lang.Override
  public dev.tandem.protocol.v1.SmsMessage getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  public dev.tandem.protocol.v1.SmsMessageOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }
  private void ensureMessagesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<dev.tandem.protocol.v1.SmsMessage> tmp = messages_;
    if (!tmp.isModifiable()) {
      messages_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setMessages(
      int index, dev.tandem.protocol.v1.SmsMessage value) {
    value.getClass();  // minimal bytecode null check
    ensureMessagesIsMutable();
    messages_.set(index, value);
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addMessages(dev.tandem.protocol.v1.SmsMessage value) {
    value.getClass();  // minimal bytecode null check
    ensureMessagesIsMutable();
    messages_.add(value);
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addMessages(
      int index, dev.tandem.protocol.v1.SmsMessage value) {
    value.getClass();  // minimal bytecode null check
    ensureMessagesIsMutable();
    messages_.add(index, value);
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  private void addAllMessages(
      java.lang.Iterable<? extends dev.tandem.protocol.v1.SmsMessage> values) {
    ensureMessagesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, messages_);
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  private void clearMessages() {
    messages_ = emptyProtobufList();
  }
  /**
   * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
   */
  private void removeMessages(int index) {
    ensureMessagesIsMutable();
    messages_.remove(index);
  }

  public static final int HIGH_WATERMARK_ID_FIELD_NUMBER = 4;
  private long highWatermarkId_;
  /**
   * <code>uint64 high_watermark_id = 4 [json_name = "highWatermarkId"];</code>
   * @return The highWatermarkId.
   */
  @java.lang.Override
  public long getHighWatermarkId() {
    return highWatermarkId_;
  }
  /**
   * <code>uint64 high_watermark_id = 4 [json_name = "highWatermarkId"];</code>
   * @param value The highWatermarkId to set.
   */
  private void setHighWatermarkId(long value) {
    
    highWatermarkId_ = value;
  }
  /**
   * <code>uint64 high_watermark_id = 4 [json_name = "highWatermarkId"];</code>
   */
  private void clearHighWatermarkId() {

    highWatermarkId_ = 0L;
  }

  public static final int BACKFILL_CURSOR_ID_FIELD_NUMBER = 5;
  private long backfillCursorId_;
  /**
   * <code>uint64 backfill_cursor_id = 5 [json_name = "backfillCursorId"];</code>
   * @return The backfillCursorId.
   */
  @java.lang.Override
  public long getBackfillCursorId() {
    return backfillCursorId_;
  }
  /**
   * <code>uint64 backfill_cursor_id = 5 [json_name = "backfillCursorId"];</code>
   * @param value The backfillCursorId to set.
   */
  private void setBackfillCursorId(long value) {
    
    backfillCursorId_ = value;
  }
  /**
   * <code>uint64 backfill_cursor_id = 5 [json_name = "backfillCursorId"];</code>
   */
  private void clearBackfillCursorId() {

    backfillCursorId_ = 0L;
  }

  public static final int BACKFILL_COMPLETE_FIELD_NUMBER = 6;
  private boolean backfillComplete_;
  /**
   * <code>bool backfill_complete = 6 [json_name = "backfillComplete"];</code>
   * @return The backfillComplete.
   */
  @java.lang.Override
  public boolean getBackfillComplete() {
    return backfillComplete_;
  }
  /**
   * <code>bool backfill_complete = 6 [json_name = "backfillComplete"];</code>
   * @param value The backfillComplete to set.
   */
  private void setBackfillComplete(boolean value) {
    
    backfillComplete_ = value;
  }
  /**
   * <code>bool backfill_complete = 6 [json_name = "backfillComplete"];</code>
   */
  private void clearBackfillComplete() {

    backfillComplete_ = false;
  }

  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static dev.tandem.protocol.v1.SmsSyncResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static dev.tandem.protocol.v1.SmsSyncResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static dev.tandem.protocol.v1.SmsSyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(dev.tandem.protocol.v1.SmsSyncResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * SmsSyncResponse: phone -&gt; Mac, one page of a sync.
   * </pre>
   *
   * Protobuf type {@code tandem.v1.SmsSyncResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        dev.tandem.protocol.v1.SmsSyncResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:tandem.v1.SmsSyncResponse)
      dev.tandem.protocol.v1.SmsSyncResponseOrBuilder {
    // Construct using dev.tandem.protocol.v1.SmsSyncResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return instance.getStatusValue();
    }
    /**
     * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
     * @param value The status to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      copyOnWrite();
      instance.setStatusValue(value);
      return this;
    }
    /**
     * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.SmsSyncStatus getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(dev.tandem.protocol.v1.SmsSyncStatus value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>.tandem.v1.SmsSyncStatus status = 1 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    @java.lang.Override
    public java.util.List<dev.tandem.protocol.v1.SmsThread> getThreadsList() {
      return java.util.Collections.unmodifiableList(
          instance.getThreadsList());
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    @java.lang.Override
    public int getThreadsCount() {
      return instance.getThreadsCount();
    }/**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.SmsThread getThreads(int index) {
      return instance.getThreads(index);
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder setThreads(
        int index, dev.tandem.protocol.v1.SmsThread value) {
      copyOnWrite();
      instance.setThreads(index, value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder setThreads(
        int index, dev.tandem.protocol.v1.SmsThread.Builder builderForValue) {
      copyOnWrite();
      instance.setThreads(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder addThreads(dev.tandem.protocol.v1.SmsThread value) {
      copyOnWrite();
      instance.addThreads(value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder addThreads(
        int index, dev.tandem.protocol.v1.SmsThread value) {
      copyOnWrite();
      instance.addThreads(index, value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder addThreads(
        dev.tandem.protocol.v1.SmsThread.Builder builderForValue) {
      copyOnWrite();
      instance.addThreads(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder addThreads(
        int index, dev.tandem.protocol.v1.SmsThread.Builder builderForValue) {
      copyOnWrite();
      instance.addThreads(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder addAllThreads(
        java.lang.Iterable<? extends dev.tandem.protocol.v1.SmsThread> values) {
      copyOnWrite();
      instance.addAllThreads(values);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder clearThreads() {
      copyOnWrite();
      instance.clearThreads();
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsThread threads = 2 [json_name = "threads"];</code>
     */
    public Builder removeThreads(int index) {
      copyOnWrite();
      instance.removeThreads(index);
      return this;
    }

    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    @java.lang.Override
    public java.util.List<dev.tandem.protocol.v1.SmsMessage> getMessagesList() {
      return java.util.Collections.unmodifiableList(
          instance.getMessagesList());
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return instance.getMessagesCount();
    }/**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    @java.lang.Override
    public dev.tandem.protocol.v1.SmsMessage getMessages(int index) {
      return instance.getMessages(index);
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder setMessages(
        int index, dev.tandem.protocol.v1.SmsMessage value) {
      copyOnWrite();
      instance.setMessages(index, value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder setMessages(
        int index, dev.tandem.protocol.v1.SmsMessage.Builder builderForValue) {
      copyOnWrite();
      instance.setMessages(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder addMessages(dev.tandem.protocol.v1.SmsMessage value) {
      copyOnWrite();
      instance.addMessages(value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder addMessages(
        int index, dev.tandem.protocol.v1.SmsMessage value) {
      copyOnWrite();
      instance.addMessages(index, value);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder addMessages(
        dev.tandem.protocol.v1.SmsMessage.Builder builderForValue) {
      copyOnWrite();
      instance.addMessages(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder addMessages(
        int index, dev.tandem.protocol.v1.SmsMessage.Builder builderForValue) {
      copyOnWrite();
      instance.addMessages(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends dev.tandem.protocol.v1.SmsMessage> values) {
      copyOnWrite();
      instance.addAllMessages(values);
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder clearMessages() {
      copyOnWrite();
      instance.clearMessages();
      return this;
    }
    /**
     * <code>repeated .tandem.v1.SmsMessage messages = 3 [json_name = "messages"];</code>
     */
    public Builder removeMessages(int index) {
      copyOnWrite();
      instance.removeMessages(index);
      return this;
    }

    /**
     * <code>uint64 high_watermark_id = 4 [json_name = "highWatermarkId"];</code>
     * @return The highWatermarkId.
     */
    @java.lang.Override
    public long getHighWatermarkId() {
      return instance.getHighWatermarkId();
    }
    /**
     * <code>uint64 high_watermark_id = 4 [json_name = "highWatermarkId"];</code>
     * @param value The highWatermarkId to set.
     * @return This builder for chaining.
     */
    public Builder setHighWatermarkId(long value) {
      copyOnWrite();
      instance.setHighWatermarkId(value);
      return this;
    }
    /**
     * <code>uint64 high_watermark_id = 4 [json_name = "highWatermarkId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHighWatermarkId() {
      copyOnWrite();
      instance.clearHighWatermarkId();
      return this;
    }

    /**
     * <code>uint64 backfill_cursor_id = 5 [json_name = "backfillCursorId"];</code>
     * @return The backfillCursorId.
     */
    @java.lang.Override
    public long getBackfillCursorId() {
      return instance.getBackfillCursorId();
    }
    /**
     * <code>uint64 backfill_cursor_id = 5 [json_name = "backfillCursorId"];</code>
     * @param value The backfillCursorId to set.
     * @return This builder for chaining.
     */
    public Builder setBackfillCursorId(long value) {
      copyOnWrite();
      instance.setBackfillCursorId(value);
      return this;
    }
    /**
     * <code>uint64 backfill_cursor_id = 5 [json_name = "backfillCursorId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBackfillCursorId() {
      copyOnWrite();
      instance.clearBackfillCursorId();
      return this;
    }

    /**
     * <code>bool backfill_complete = 6 [json_name = "backfillComplete"];</code>
     * @return The backfillComplete.
     */
    @java.lang.Override
    public boolean getBackfillComplete() {
      return instance.getBackfillComplete();
    }
    /**
     * <code>bool backfill_complete = 6 [json_name = "backfillComplete"];</code>
     * @param value The backfillComplete to set.
     * @return This builder for chaining.
     */
    public Builder setBackfillComplete(boolean value) {
      copyOnWrite();
      instance.setBackfillComplete(value);
      return this;
    }
    /**
     * <code>bool backfill_complete = 6 [json_name = "backfillComplete"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBackfillComplete() {
      copyOnWrite();
      instance.clearBackfillComplete();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tandem.v1.SmsSyncResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new dev.tandem.protocol.v1.SmsSyncResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "status_",
            "threads_",
            dev.tandem.protocol.v1.SmsThread.class,
            "messages_",
            dev.tandem.protocol.v1.SmsMessage.class,
            "highWatermarkId_",
            "backfillCursorId_",
            "backfillComplete_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0002\u0000\u0001\f\u0002\u001b" +
              "\u0003\u001b\u0004\u0003\u0005\u0003\u0006\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<dev.tandem.protocol.v1.SmsSyncResponse> parser = PARSER;
        if (parser == null) {
          synchronized (dev.tandem.protocol.v1.SmsSyncResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<dev.tandem.protocol.v1.SmsSyncResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:tandem.v1.SmsSyncResponse)
  private static final dev.tandem.protocol.v1.SmsSyncResponse DEFAULT_INSTANCE;
  static {
    SmsSyncResponse defaultInstance = new SmsSyncResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SmsSyncResponse.class, defaultInstance);
  }

  public static dev.tandem.protocol.v1.SmsSyncResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SmsSyncResponse> PARSER;

  public static com.google.protobuf.Parser<SmsSyncResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

