// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/notify.proto
// Protobuf Java Version: 4.35.0

package dev.tandem.protocol.v1;

/**
 * <pre>
 * Visibility: mirrors the Android notification's lock-screen visibility (PRD F-5.4). A
 * VISIBILITY_SECRET notification is forwarded in redacted form (E30-11): title = the app name,
 * text = "", messaging_style_senders = [] — the phone never sends the real content in that case,
 * so no receiver-side redaction is required.
 * </pre>
 *
 * Protobuf enum {@code tandem.v1.Visibility}
 */
@com.google.protobuf.Generated
public enum Visibility
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>VISIBILITY_UNSPECIFIED = 0;</code>
   */
  VISIBILITY_UNSPECIFIED(0),
  /**
   * <code>VISIBILITY_PUBLIC = 1;</code>
   */
  VISIBILITY_PUBLIC(1),
  /**
   * <code>VISIBILITY_PRIVATE = 2;</code>
   */
  VISIBILITY_PRIVATE(2),
  /**
   * <code>VISIBILITY_SECRET = 3;</code>
   */
  VISIBILITY_SECRET(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>VISIBILITY_UNSPECIFIED = 0;</code>
   */
  public static final int VISIBILITY_UNSPECIFIED_VALUE = 0;
  /**
   * <code>VISIBILITY_PUBLIC = 1;</code>
   */
  public static final int VISIBILITY_PUBLIC_VALUE = 1;
  /**
   * <code>VISIBILITY_PRIVATE = 2;</code>
   */
  public static final int VISIBILITY_PRIVATE_VALUE = 2;
  /**
   * <code>VISIBILITY_SECRET = 3;</code>
   */
  public static final int VISIBILITY_SECRET_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Visibility valueOf(int value) {
    return forNumber(value);
  }

  public static Visibility forNumber(int value) {
    switch (value) {
      case 0: return VISIBILITY_UNSPECIFIED;
      case 1: return VISIBILITY_PUBLIC;
      case 2: return VISIBILITY_PRIVATE;
      case 3: return VISIBILITY_SECRET;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Visibility>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Visibility> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Visibility>() {
          @java.lang.Override
          public Visibility findValueByNumber(int number) {
            return Visibility.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return VisibilityVerifier.INSTANCE;
  }

  private static final class VisibilityVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new VisibilityVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return Visibility.forNumber(number) != null;
          }
        };

  private final int value;

  private Visibility(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tandem.v1.Visibility)
}

