// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tandem/v1/envelope.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Channel: docs/protocol/SPEC.md #framing-and-envelope. CHANNEL_UNSPECIFIED = 0 is never valid
/// on the wire; receiving it (or any value outside this list) is rejected UNKNOWN_CHANNEL
/// (#errors-and-close-codes, MALFORMED_FRAME). The channel set is closed at exactly these nine
/// values (docs/planning/backlog/phase-0.yaml E01-04 acceptance — there is no PHOTOS channel,
/// photo-browser messages ride FILES). Numbers are frozen once released: never renumber or reuse.
/// Values are prefixed CHANNEL_* to satisfy buf lint's STANDARD ENUM_VALUE_PREFIX rule; SPEC.md
/// and the backlog refer to the same channels by their unprefixed names (CONTROL, NOTIFY, ...).
nonisolated enum Tandem_V1_Channel: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case control // = 1
  case notify // = 2
  case clipboard // = 3
  case files // = 4
  case sms // = 5
  case contacts // = 6
  case calls // = 7
  case input // = 8
  case status // = 9
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .control
    case 2: self = .notify
    case 3: self = .clipboard
    case 4: self = .files
    case 5: self = .sms
    case 6: self = .contacts
    case 7: self = .calls
    case 8: self = .input
    case 9: self = .status
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .control: return 1
    case .notify: return 2
    case .clipboard: return 3
    case .files: return 4
    case .sms: return 5
    case .contacts: return 6
    case .calls: return 7
    case .input: return 8
    case .status: return 9
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Tandem_V1_Channel] = [
    .unspecified,
    .control,
    .notify,
    .clipboard,
    .files,
    .sms,
    .contacts,
    .calls,
    .input,
    .status,
  ]

}

/// Envelope: docs/protocol/SPEC.md #framing-and-envelope. Every frame (length-prefixed per that
/// section) on every mTLS connection carries exactly one Envelope.
nonisolated struct Tandem_V1_Envelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var channel: Tandem_V1_Channel = .unspecified

  /// Per-channel, per-direction counter maintained independently by each side. The first frame a
  /// side sends on a channel carries seq = 1; seq = 0 is never valid on the wire
  /// (#framing-and-envelope "Envelope fields").
  var seq: UInt64 = 0

  /// Highest seq received in contiguous order from the peer on this channel; 0 before anything
  /// has arrived on that channel in that direction (#framing-and-envelope "Envelope fields").
  var ack: UInt64 = 0

  var payload: Tandem_V1_Envelope.OneOf_Payload? = nil

  var deviceStatus: Tandem_V1_DeviceStatus {
    get {
      if case .deviceStatus(let v)? = payload {return v}
      return Tandem_V1_DeviceStatus()
    }
    set {payload = .deviceStatus(newValue)}
  }

  var ring: Tandem_V1_Ring {
    get {
      if case .ring(let v)? = payload {return v}
      return Tandem_V1_Ring()
    }
    set {payload = .ring(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Payload: Equatable, Sendable {
    case deviceStatus(Tandem_V1_DeviceStatus)
    case ring(Tandem_V1_Ring)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tandem.v1"

nonisolated extension Tandem_V1_Channel: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CHANNEL_UNSPECIFIED\0\u{1}CHANNEL_CONTROL\0\u{1}CHANNEL_NOTIFY\0\u{1}CHANNEL_CLIPBOARD\0\u{1}CHANNEL_FILES\0\u{1}CHANNEL_SMS\0\u{1}CHANNEL_CONTACTS\0\u{1}CHANNEL_CALLS\0\u{1}CHANNEL_INPUT\0\u{1}CHANNEL_STATUS\0")
}

nonisolated extension Tandem_V1_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Envelope"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}channel\0\u{1}seq\0\u{1}ack\0\u{4}\u{11}device_status\0\u{1}ring\0\u{c}\u{4}\u{6}\u{c}\u{a}\u{a}\u{c}\u{16}\u{8}\u{c}\u{1e}\u{a}\u{c}(\u{a}\u{c}2\u{a}\u{c}<\u{a}\u{c}F\u{1}\u{a}\u{c}P\u{1}\u{a}\u{c}Z\u{1}\u{a}\u{c}d\u{1}\u{a}\u{c}n\u{1}\u{a}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.channel) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.seq) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.ack) }()
      case 20: try {
        var v: Tandem_V1_DeviceStatus?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .deviceStatus(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .deviceStatus(v)
        }
      }()
      case 21: try {
        var v: Tandem_V1_Ring?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .ring(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .ring(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.channel != .unspecified {
      try visitor.visitSingularEnumField(value: self.channel, fieldNumber: 1)
    }
    if self.seq != 0 {
      try visitor.visitSingularUInt64Field(value: self.seq, fieldNumber: 2)
    }
    if self.ack != 0 {
      try visitor.visitSingularUInt64Field(value: self.ack, fieldNumber: 3)
    }
    switch self.payload {
    case .deviceStatus?: try {
      guard case .deviceStatus(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    }()
    case .ring?: try {
      guard case .ring(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tandem_V1_Envelope, rhs: Tandem_V1_Envelope) -> Bool {
    if lhs.channel != rhs.channel {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs.ack != rhs.ack {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
