// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tandem/v1/notify.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Visibility: mirrors the Android notification's lock-screen visibility (PRD F-5.4). A
/// VISIBILITY_SECRET notification is forwarded in redacted form (E30-11): title = the app name,
/// text = "", messaging_style_senders = [] — the phone never sends the real content in that case,
/// so no receiver-side redaction is required.
public nonisolated enum Tandem_V1_Visibility: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case `public` // = 1
  case `private` // = 2
  case secret // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .public
    case 2: self = .private
    case 3: self = .secret
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .public: return 1
    case .private: return 2
    case .secret: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Tandem_V1_Visibility] = [
    .unspecified,
    .public,
    .private,
    .secret,
  ]

}

/// NotificationPosted: PRD F-5.1 — the phone sends this when a notification is posted or updated.
/// Sent directly as the Envelope payload (no wrapper message needed).
public nonisolated struct Tandem_V1_NotificationPosted: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Stable identifier for this notification (phone-assigned), reused by NotificationAction,
  /// NotificationDismiss, and NotificationActionResult to refer back to it. A second
  /// NotificationPosted with the same key updates the Mac's presentation of the same notification
  /// rather than stacking a new one.
  public var key: String = String()

  public var packageName: String = String()

  public var appVersionCode: Int64 = 0

  /// Display cap: <= 256 characters (#timeouts-connection-limits-and-resource-caps, E01-22);
  /// sanitized per #untrusted-peer-strings-display-sanitization (E01-23) before display.
  public var title: String = String()

  /// Display cap: <= 4096 characters (E01-22); sanitized as a `body` field (E01-23).
  public var text: String = String()

  /// MessagingStyle sender names, message order preserved. Cap: <= 25 entries of <= 64 characters
  /// each (E01-22); each entry is sanitized as a `name` field (E01-23).
  public var messagingStyleSenders: [String] = []

  public var visibility: Tandem_V1_Visibility = .unspecified

  /// True when the source notification has an icon; the icon bytes themselves arrive separately
  /// as IconData keyed by package_name + app_version_code (icons are cached per app version, not
  /// per notification, E30-05).
  public var hasIcon_p: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// IconData: PRD F-5.1 — an app icon, sent so the Mac can present notifications with the source
/// app's icon without asking again for every post from the same app version.
public nonisolated struct Tandem_V1_IconData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var packageName: String = String()

  public var versionCode: Int64 = 0

  /// Cap: <= 64 KiB and <= 256x256 px (E01-22); over-cap data is discarded and a placeholder icon
  /// used instead (E30-05) rather than rejected at the protocol layer.
  public var pngBytes: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// NotificationAction: PRD F-5.2 — the Mac sends this when the user taps an action (or submits a
/// reply) on a mirrored notification.
public nonisolated struct Tandem_V1_NotificationAction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: String = String()

  /// Index into the source notification's action list, in the order NotificationPosted's source
  /// notification declared them.
  public var actionIndex: Int32 = 0

  /// Present only for a RemoteInput-capable action the user replied to; empty otherwise. Cap:
  /// <= 4096 characters (E01-22); sanitized as a `body` field (E01-23) before being shown back to
  /// the user (e.g. in a sent-reply confirmation).
  public var replyText: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// NotificationDismiss: PRD F-5.3 — either side sends this when a notification is dismissed, so
/// the other side removes its copy. `origin` records which side dismissed it, so the receiver
/// never re-forwards a dismissal it only just applied locally (avoiding an echo loop, E30-10,
/// E30-18).
public nonisolated struct Tandem_V1_NotificationDismiss: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: String = String()

  public var origin: Tandem_V1_NotificationDismiss.Origin = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Origin: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case android // = 1
    case macos // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .android
      case 2: self = .macos
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .android: return 1
      case .macos: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Tandem_V1_NotificationDismiss.Origin] = [
      .unspecified,
      .android,
      .macos,
    ]

  }

  public init() {}
}

/// NotificationActionResult: PRD F-5.2 — the phone answers every received NotificationAction with
/// this, so the Mac can report a reply/action as sent, or "no longer available" if the source
/// notification was already gone (UC-09 alternate).
public nonisolated struct Tandem_V1_NotificationActionResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: String = String()

  public var status: Tandem_V1_NotificationActionResult.Status = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum Status: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case ok // = 1
    case gone // = 2
    case failed // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .ok
      case 2: self = .gone
      case 3: self = .failed
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .ok: return 1
      case .gone: return 2
      case .failed: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Tandem_V1_NotificationActionResult.Status] = [
      .unspecified,
      .ok,
      .gone,
      .failed,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tandem.v1"

nonisolated extension Tandem_V1_Visibility: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VISIBILITY_UNSPECIFIED\0\u{1}VISIBILITY_PUBLIC\0\u{1}VISIBILITY_PRIVATE\0\u{1}VISIBILITY_SECRET\0")
}

nonisolated extension Tandem_V1_NotificationPosted: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NotificationPosted"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{3}package_name\0\u{3}app_version_code\0\u{1}title\0\u{1}text\0\u{3}messaging_style_senders\0\u{1}visibility\0\u{3}has_icon\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.packageName) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.appVersionCode) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.text) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.messagingStyleSenders) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.visibility) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.hasIcon_p) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if !self.packageName.isEmpty {
      try visitor.visitSingularStringField(value: self.packageName, fieldNumber: 2)
    }
    if self.appVersionCode != 0 {
      try visitor.visitSingularInt64Field(value: self.appVersionCode, fieldNumber: 3)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 4)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 5)
    }
    if !self.messagingStyleSenders.isEmpty {
      try visitor.visitRepeatedStringField(value: self.messagingStyleSenders, fieldNumber: 6)
    }
    if self.visibility != .unspecified {
      try visitor.visitSingularEnumField(value: self.visibility, fieldNumber: 7)
    }
    if self.hasIcon_p != false {
      try visitor.visitSingularBoolField(value: self.hasIcon_p, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_NotificationPosted, rhs: Tandem_V1_NotificationPosted) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.packageName != rhs.packageName {return false}
    if lhs.appVersionCode != rhs.appVersionCode {return false}
    if lhs.title != rhs.title {return false}
    if lhs.text != rhs.text {return false}
    if lhs.messagingStyleSenders != rhs.messagingStyleSenders {return false}
    if lhs.visibility != rhs.visibility {return false}
    if lhs.hasIcon_p != rhs.hasIcon_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_IconData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IconData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}package_name\0\u{3}version_code\0\u{3}png_bytes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.packageName) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.versionCode) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.pngBytes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.packageName.isEmpty {
      try visitor.visitSingularStringField(value: self.packageName, fieldNumber: 1)
    }
    if self.versionCode != 0 {
      try visitor.visitSingularInt64Field(value: self.versionCode, fieldNumber: 2)
    }
    if !self.pngBytes.isEmpty {
      try visitor.visitSingularBytesField(value: self.pngBytes, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_IconData, rhs: Tandem_V1_IconData) -> Bool {
    if lhs.packageName != rhs.packageName {return false}
    if lhs.versionCode != rhs.versionCode {return false}
    if lhs.pngBytes != rhs.pngBytes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_NotificationAction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NotificationAction"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{3}action_index\0\u{3}reply_text\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.actionIndex) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.replyText) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if self.actionIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.actionIndex, fieldNumber: 2)
    }
    if !self.replyText.isEmpty {
      try visitor.visitSingularStringField(value: self.replyText, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_NotificationAction, rhs: Tandem_V1_NotificationAction) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.actionIndex != rhs.actionIndex {return false}
    if lhs.replyText != rhs.replyText {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_NotificationDismiss: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NotificationDismiss"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}origin\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.origin) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if self.origin != .unspecified {
      try visitor.visitSingularEnumField(value: self.origin, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_NotificationDismiss, rhs: Tandem_V1_NotificationDismiss) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.origin != rhs.origin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_NotificationDismiss.Origin: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ORIGIN_UNSPECIFIED\0\u{1}ORIGIN_ANDROID\0\u{1}ORIGIN_MACOS\0")
}

nonisolated extension Tandem_V1_NotificationActionResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NotificationActionResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}status\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_NotificationActionResult, rhs: Tandem_V1_NotificationActionResult) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_NotificationActionResult.Status: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STATUS_UNSPECIFIED\0\u{1}STATUS_OK\0\u{1}STATUS_GONE\0\u{1}STATUS_FAILED\0")
}
