// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tandem/v1/pairing.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PairRejectedReason: the wire-collapsed reason carried by PairRejected
/// (docs/planning/decisions.md D-72, cycle 4 oracle collapse). No wire value distinguishes a bad
/// proof from an expired window from a malformed request (D-17); the E01-05 local reasons
/// (EXPIRED, BAD_PROOF, MALFORMED) never appear on the wire, and local reason TIMEOUT sends no
/// PairRejected at all (D-72).
public nonisolated enum Tandem_V1_PairRejectedReason: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Never legal on the wire; fatal for a receiver, like any other proto3 zero-value default
  /// relied on as a real signal.
  case unspecified // = 0

  /// The owner explicitly declined (clicked Don't Pair, pressed Escape, or closed the dialog).
  case rejectedByOwner // = 1

  /// Every other local rejection reason a connection can actually receive: EXPIRED, BAD_PROOF, or
  /// MALFORMED.
  case pairingUnavailable // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .rejectedByOwner
    case 2: self = .pairingUnavailable
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .rejectedByOwner: return 1
    case .pairingUnavailable: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Tandem_V1_PairRejectedReason] = [
    .unspecified,
    .rejectedByOwner,
    .pairingUnavailable,
  ]

}

/// PairChallenge: docs/protocol/SPEC.md #pairing "Frame order on a pairing-candidate connection"
/// (docs/planning/decisions.md D-67). The Mac's in-band channel-binding challenge, sent
/// unconditionally as the first CONTROL frame after the VersionHello exchange completes on every
/// pairing-candidate connection, on every platform and API level — never a fallback gated on the
/// E03-04 exporter spike outcome (D-67 supersedes D-15).
public nonisolated struct Tandem_V1_PairChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Exactly 32 bytes (256 bits) from a CSPRNG, generated fresh per pairing-candidate connection.
  /// This is the `cb` input to both the proof and confirmation-code formulas (#pairing "Proof
  /// computation", "Confirmation code").
  public var challenge: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// DeviceInfo: the phone's self-reported identity shown to the owner in the Mac's mutual-
/// confirmation dialog (#pairing "Mutual confirmation"), sanitized for display before use
/// (#untrusted-peer-strings-display-sanitization, E01-23) and never trusted for any decision.
/// Cycle 4: no IMEI, serial, ANDROID_ID, account, or other stable hardware identifier.
public nonisolated struct Tandem_V1_DeviceInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// At most 64 UTF-8 bytes.
  public var displayName: String = String()

  /// At most 64 UTF-8 bytes.
  public var model: String = String()

  public var appVersion: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// PairRequest: docs/protocol/SPEC.md #pairing "Frame order on a pairing-candidate connection".
/// The phone's reply to PairChallenge, due within 10 s of the VersionHello exchange completing.
/// Carries no public key or fingerprint field: the phone's key comes only from the client
/// certificate actually seen on this connection's TLS handshake (#pairing "Proof computation"),
/// never from any field here.
public nonisolated struct Tandem_V1_PairRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceInfo: Tandem_V1_DeviceInfo {
    get {_deviceInfo ?? Tandem_V1_DeviceInfo()}
    set {_deviceInfo = newValue}
  }
  /// Returns true if `deviceInfo` has been explicitly set.
  public var hasDeviceInfo: Bool {self._deviceInfo != nil}
  /// Clears the value of `deviceInfo`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceInfo() {self._deviceInfo = nil}

  /// HMAC-SHA256(secret, transcript) per #pairing "Proof computation"; the Mac recomputes and
  /// compares this in constant time (invariant 6).
  public var proof: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _deviceInfo: Tandem_V1_DeviceInfo? = nil
}

/// PairAccepted: docs/protocol/SPEC.md #pairing "Mutual confirmation". Sent by the Mac only after
/// the owner explicitly clicks Pair; no fields.
public nonisolated struct Tandem_V1_PairAccepted: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// PairRejected: docs/protocol/SPEC.md #pairing "PairRejected wire collapse". Sent immediately
/// before the PAIRING_FAILED close (#errors-and-close-codes).
public nonisolated struct Tandem_V1_PairRejected: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reason: Tandem_V1_PairRejectedReason = .unspecified

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Revoke: docs/protocol/SPEC.md #pairing "Mutual confirmation". Always means "delete the record
/// of the peer authenticated on this session"; can never name another peer, so it has no fields.
public nonisolated struct Tandem_V1_Revoke: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tandem.v1"

nonisolated extension Tandem_V1_PairRejectedReason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PAIR_REJECTED_REASON_UNSPECIFIED\0\u{1}PAIR_REJECTED_REASON_REJECTED_BY_OWNER\0\u{1}PAIR_REJECTED_REASON_PAIRING_UNAVAILABLE\0")
}

nonisolated extension Tandem_V1_PairChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairChallenge"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}challenge\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.challenge) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.challenge.isEmpty {
      try visitor.visitSingularBytesField(value: self.challenge, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_PairChallenge, rhs: Tandem_V1_PairChallenge) -> Bool {
    if lhs.challenge != rhs.challenge {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_DeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}display_name\0\u{1}model\0\u{3}app_version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.appVersion) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 1)
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 2)
    }
    if !self.appVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.appVersion, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_DeviceInfo, rhs: Tandem_V1_DeviceInfo) -> Bool {
    if lhs.displayName != rhs.displayName {return false}
    if lhs.model != rhs.model {return false}
    if lhs.appVersion != rhs.appVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_PairRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}device_info\0\u{1}proof\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._deviceInfo) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.proof) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._deviceInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.proof.isEmpty {
      try visitor.visitSingularBytesField(value: self.proof, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_PairRequest, rhs: Tandem_V1_PairRequest) -> Bool {
    if lhs._deviceInfo != rhs._deviceInfo {return false}
    if lhs.proof != rhs.proof {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_PairAccepted: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairAccepted"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_PairAccepted, rhs: Tandem_V1_PairAccepted) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_PairRejected: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PairRejected"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reason\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.reason != .unspecified {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_PairRejected, rhs: Tandem_V1_PairRejected) -> Bool {
    if lhs.reason != rhs.reason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_Revoke: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Revoke"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Tandem_V1_Revoke, rhs: Tandem_V1_Revoke) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
