// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: tandem/v1/status.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// NetworkType: the phone's current network connectivity, part of DeviceStatus (PRD F-4.3).
nonisolated enum Tandem_V1_NetworkType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case wifi // = 1
  case cellular // = 2
  case offline // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .wifi
    case 2: self = .cellular
    case 3: self = .offline
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .wifi: return 1
    case .cellular: return 2
    case .offline: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Tandem_V1_NetworkType] = [
    .unspecified,
    .wifi,
    .cellular,
    .offline,
  ]

}

/// DeviceStatus: PRD F-4.3 — the phone publishes this on the STATUS channel on change and at
/// most every 60 s. Sent directly as the Envelope payload (no wrapper message needed).
nonisolated struct Tandem_V1_DeviceStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Battery charge percentage, 0-100.
  var batteryLevel: Int32 = 0

  var isCharging: Bool = false

  var networkType: Tandem_V1_NetworkType = .unspecified

  /// Signal strength, 0 (none) to 4 (full bars); meaningless (0) when network_type is
  /// NETWORK_TYPE_OFFLINE.
  var signalLevel: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Ring: PRD F-4.4 — the Mac sends this to make the phone play an alarm at max volume,
/// overriding DND, until dismissed. No fields: ringing is idempotent while already in progress,
/// and the alarm starts at most twice per 10 s (docs/planning/decisions.md D-62), so repeated
/// delivery of this same empty message is intentionally indistinguishable from the first.
nonisolated struct Tandem_V1_Ring: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tandem.v1"

nonisolated extension Tandem_V1_NetworkType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NETWORK_TYPE_UNSPECIFIED\0\u{1}NETWORK_TYPE_WIFI\0\u{1}NETWORK_TYPE_CELLULAR\0\u{1}NETWORK_TYPE_OFFLINE\0")
}

nonisolated extension Tandem_V1_DeviceStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeviceStatus"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}battery_level\0\u{3}is_charging\0\u{3}network_type\0\u{3}signal_level\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.batteryLevel) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isCharging) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.networkType) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.signalLevel) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.batteryLevel != 0 {
      try visitor.visitSingularInt32Field(value: self.batteryLevel, fieldNumber: 1)
    }
    if self.isCharging != false {
      try visitor.visitSingularBoolField(value: self.isCharging, fieldNumber: 2)
    }
    if self.networkType != .unspecified {
      try visitor.visitSingularEnumField(value: self.networkType, fieldNumber: 3)
    }
    if self.signalLevel != 0 {
      try visitor.visitSingularInt32Field(value: self.signalLevel, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tandem_V1_DeviceStatus, rhs: Tandem_V1_DeviceStatus) -> Bool {
    if lhs.batteryLevel != rhs.batteryLevel {return false}
    if lhs.isCharging != rhs.isCharging {return false}
    if lhs.networkType != rhs.networkType {return false}
    if lhs.signalLevel != rhs.signalLevel {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Tandem_V1_Ring: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Ring"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Tandem_V1_Ring, rhs: Tandem_V1_Ring) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
