// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/clipboard.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializeclipboardText")
public inline fun clipboardText(block: dev.tandem.protocol.v1.ClipboardTextKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.ClipboardText =
  dev.tandem.protocol.v1.ClipboardTextKt.Dsl._create(dev.tandem.protocol.v1.ClipboardText.newBuilder()).apply { block() }._build()
/**
 * ```
 * ClipboardText: PRD F-6.1, F-6.2, F-6.3 — either side sends this when its clipboard/pasteboard
 * text changes and qualifies to be forwarded. Sent directly as the Envelope payload (no wrapper
 * message needed). Concealed/transient source items and items over the size cap are filtered out
 * on the sending side before this message is ever built (E31-03, E31-04, E31-06) — this message
 * type carries only content the sender has already decided qualifies.
 * ```
 *
 * Protobuf type `tandem.v1.ClipboardText`
 */
public object ClipboardTextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.ClipboardText.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.ClipboardText.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.ClipboardText = _builder.build()

    /**
     * ```
     * Identifies which side last wrote this clipboard content: "macos" or "android" (E31-04,
     * E31-06). A plain string rather than an enum (unlike NotificationDismiss.Origin/
     * RingStop.Origin) because it is only ever compared for equality by the E31-08/E31-14 loop
     * guard, never branched on by value. Used together with content_hash (below) for echo-loop
     * prevention (docs/protocol/SPEC.md #clipboard-channel).
     * ```
     *
     * `string origin_tag = 1 [json_name = "originTag"];`
     */
    public var originTag: kotlin.String
      @kotlin.jvm.JvmName("getOriginTag")
        get() = _builder.originTag
      @kotlin.jvm.JvmName("setOriginTag")
        set(value) {
        _builder.originTag = value
      }
    /**
     * ```
     * Identifies which side last wrote this clipboard content: "macos" or "android" (E31-04,
     * E31-06). A plain string rather than an enum (unlike NotificationDismiss.Origin/
     * RingStop.Origin) because it is only ever compared for equality by the E31-08/E31-14 loop
     * guard, never branched on by value. Used together with content_hash (below) for echo-loop
     * prevention (docs/protocol/SPEC.md #clipboard-channel).
     * ```
     *
     * `string origin_tag = 1 [json_name = "originTag"];`
     */
    public fun clearOriginTag() {
      _builder.clearOriginTag()
    }

    /**
     * ```
     * SHA-256 digest (32 bytes) of `text`'s UTF-8 bytes (docs/protocol/SPEC.md #clipboard-channel).
     * Paired with origin_tag by the E31-08/E31-14 loop guard: a side that receives and writes a
     * clip records this pair, so when its own poller re-detects the same content it recognizes its
     * own just-written content and does not send it back.
     * ```
     *
     * `bytes content_hash = 2 [json_name = "contentHash"];`
     */
    public var contentHash: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getContentHash")
        get() = _builder.contentHash
      @kotlin.jvm.JvmName("setContentHash")
        set(value) {
        _builder.contentHash = value
      }
    /**
     * ```
     * SHA-256 digest (32 bytes) of `text`'s UTF-8 bytes (docs/protocol/SPEC.md #clipboard-channel).
     * Paired with origin_tag by the E31-08/E31-14 loop guard: a side that receives and writes a
     * clip records this pair, so when its own poller re-detects the same content it recognizes its
     * own just-written content and does not send it back.
     * ```
     *
     * `bytes content_hash = 2 [json_name = "contentHash"];`
     */
    public fun clearContentHash() {
      _builder.clearContentHash()
    }

    /**
     * ```
     * UTF-8 clipboard text. Hard cap: exactly 1,048,576 bytes (1 MiB;
     * docs/protocol/SPEC.md #timeouts-connection-limits-and-resource-caps "Feature caps" and
     * #clipboard-channel). Oversize text MUST be rejected, never truncated (E31-04, E31-06).
     * ```
     *
     * `string text = 3 [json_name = "text"];`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * ```
     * UTF-8 clipboard text. Hard cap: exactly 1,048,576 bytes (1 MiB;
     * docs/protocol/SPEC.md #timeouts-connection-limits-and-resource-caps "Feature caps" and
     * #clipboard-channel). Oversize text MUST be rejected, never truncated (E31-04, E31-06).
     * ```
     *
     * `string text = 3 [json_name = "text"];`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * ```
     * True when this content originated from a source the sender treats as sensitive (e.g. an
     * Android password manager setting EXTRA_IS_SENSITIVE; PRD F-6.2, F-6.3). A receiver writes a
     * sensitive clip with the org.nspasteboard.ConcealedType and org.nspasteboard.TransientType
     * markers (E31-13) so clipboard managers and this protocol's own poller skip it. `text` is
     * never written to a log in a release build (invariant 7) regardless of this flag's value.
     * ```
     *
     * `bool sensitive = 4 [json_name = "sensitive"];`
     */
    public var sensitive: kotlin.Boolean
      @kotlin.jvm.JvmName("getSensitive")
        get() = _builder.sensitive
      @kotlin.jvm.JvmName("setSensitive")
        set(value) {
        _builder.sensitive = value
      }
    /**
     * ```
     * True when this content originated from a source the sender treats as sensitive (e.g. an
     * Android password manager setting EXTRA_IS_SENSITIVE; PRD F-6.2, F-6.3). A receiver writes a
     * sensitive clip with the org.nspasteboard.ConcealedType and org.nspasteboard.TransientType
     * markers (E31-13) so clipboard managers and this protocol's own poller skip it. `text` is
     * never written to a log in a release build (invariant 7) regardless of this flag's value.
     * ```
     *
     * `bool sensitive = 4 [json_name = "sensitive"];`
     */
    public fun clearSensitive() {
      _builder.clearSensitive()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.ClipboardText.copy(block: `dev.tandem.protocol.v1`.ClipboardTextKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.ClipboardText =
  `dev.tandem.protocol.v1`.ClipboardTextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

