// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/contacts.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializecontactsSyncResponse")
public inline fun contactsSyncResponse(block: dev.tandem.protocol.v1.ContactsSyncResponseKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.ContactsSyncResponse =
  dev.tandem.protocol.v1.ContactsSyncResponseKt.Dsl._create(dev.tandem.protocol.v1.ContactsSyncResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * ContactsSyncResponse: PRD F-8.3, UC-18, UC-19, UC-20, UC-21 -- the phone's answer to a
 * ContactsSyncRequest, possibly paginated (`complete = false` while more pages follow;
 * docs/protocol/SPEC.md #contacts-channel "Sync"). `deletedContactIds` names contacts removed from
 * the phone's store since `sinceUpdatedAtMs` (tombstones, UC-20). `watermarkMs` is the
 * Mac-authoritative watermark the Mac should persist and echo back as the next
 * ContactsSyncRequest.sinceUpdatedAtMs once `complete = true` (docs/protocol/SPEC.md
 * #contacts-channel "Watermark").
 * ```
 *
 * Protobuf type `tandem.v1.ContactsSyncResponse`
 */
public object ContactsSyncResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.ContactsSyncResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.ContactsSyncResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.ContactsSyncResponse = _builder.build()

    /**
     * `.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];`
     */
    public var status: dev.tandem.protocol.v1.ContactsSyncStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.tandem.v1.ContactsSyncStatus status = 1 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ContactsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];`
     */
     public val contacts: com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.Contact, ContactsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.contactsList
      )
    /**
     * `repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];`
     * @param value The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addContacts")
    public fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.Contact, ContactsProxy>.add(value: dev.tandem.protocol.v1.Contact) {
      _builder.addContacts(value)
    }
    /**
     * `repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];`
     * @param value The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignContacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.Contact, ContactsProxy>.plusAssign(value: dev.tandem.protocol.v1.Contact) {
      add(value)
    }
    /**
     * `repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];`
     * @param values The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllContacts")
    public fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.Contact, ContactsProxy>.addAll(values: kotlin.collections.Iterable<dev.tandem.protocol.v1.Contact>) {
      _builder.addAllContacts(values)
    }
    /**
     * `repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];`
     * @param values The contacts to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllContacts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.Contact, ContactsProxy>.plusAssign(values: kotlin.collections.Iterable<dev.tandem.protocol.v1.Contact>) {
      addAll(values)
    }
    /**
     * `repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];`
     * @param index The index to set the value at.
     * @param value The contacts to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setContacts")
    public operator fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.Contact, ContactsProxy>.set(index: kotlin.Int, value: dev.tandem.protocol.v1.Contact) {
      _builder.setContacts(index, value)
    }
    /**
     * `repeated .tandem.v1.Contact contacts = 2 [json_name = "contacts"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearContacts")
    public fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.Contact, ContactsProxy>.clear() {
      _builder.clearContacts()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DeletedContactIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];`
     * @return A list containing the deletedContactIds.
     */
    public val deletedContactIds: com.google.protobuf.kotlin.DslList<kotlin.String, DeletedContactIdsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.deletedContactIdsList
      )
    /**
     * `repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];`
     * @param value The deletedContactIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addDeletedContactIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DeletedContactIdsProxy>.add(value: kotlin.String) {
      _builder.addDeletedContactIds(value)
    }
    /**
     * `repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];`
     * @param value The deletedContactIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignDeletedContactIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DeletedContactIdsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];`
     * @param values The deletedContactIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllDeletedContactIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DeletedContactIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllDeletedContactIds(values)
    }
    /**
     * `repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];`
     * @param values The deletedContactIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllDeletedContactIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DeletedContactIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];`
     * @param index The index to set the value at.
     * @param value The deletedContactIds to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDeletedContactIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DeletedContactIdsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setDeletedContactIds(index, value)
    }/**
     * `repeated string deleted_contact_ids = 3 [json_name = "deletedContactIds"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDeletedContactIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DeletedContactIdsProxy>.clear() {
      _builder.clearDeletedContactIds()
    }
    /**
     * `uint64 watermark_ms = 4 [json_name = "watermarkMs"];`
     */
    public var watermarkMs: kotlin.Long
      @kotlin.jvm.JvmName("getWatermarkMs")
        get() = _builder.watermarkMs
      @kotlin.jvm.JvmName("setWatermarkMs")
        set(value) {
        _builder.watermarkMs = value
      }
    /**
     * `uint64 watermark_ms = 4 [json_name = "watermarkMs"];`
     */
    public fun clearWatermarkMs() {
      _builder.clearWatermarkMs()
    }

    /**
     * `bool complete = 5 [json_name = "complete"];`
     */
    public var complete: kotlin.Boolean
      @kotlin.jvm.JvmName("getComplete")
        get() = _builder.complete
      @kotlin.jvm.JvmName("setComplete")
        set(value) {
        _builder.complete = value
      }
    /**
     * `bool complete = 5 [json_name = "complete"];`
     */
    public fun clearComplete() {
      _builder.clearComplete()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.ContactsSyncResponse.copy(block: `dev.tandem.protocol.v1`.ContactsSyncResponseKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.ContactsSyncResponse =
  `dev.tandem.protocol.v1`.ContactsSyncResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

