// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/status.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializedeviceStatus")
public inline fun deviceStatus(block: dev.tandem.protocol.v1.DeviceStatusKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.DeviceStatus =
  dev.tandem.protocol.v1.DeviceStatusKt.Dsl._create(dev.tandem.protocol.v1.DeviceStatus.newBuilder()).apply { block() }._build()
/**
 * ```
 * DeviceStatus: PRD F-4.3 — the phone publishes this on the STATUS channel on change and at
 * most every 60 s. Sent directly as the Envelope payload (no wrapper message needed).
 * ```
 *
 * Protobuf type `tandem.v1.DeviceStatus`
 */
public object DeviceStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.DeviceStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.DeviceStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.DeviceStatus = _builder.build()

    /**
     * ```
     * Battery charge percentage, 0-100.
     * ```
     *
     * `int32 battery_level = 1 [json_name = "batteryLevel"];`
     */
    public var batteryLevel: kotlin.Int
      @kotlin.jvm.JvmName("getBatteryLevel")
        get() = _builder.batteryLevel
      @kotlin.jvm.JvmName("setBatteryLevel")
        set(value) {
        _builder.batteryLevel = value
      }
    /**
     * ```
     * Battery charge percentage, 0-100.
     * ```
     *
     * `int32 battery_level = 1 [json_name = "batteryLevel"];`
     */
    public fun clearBatteryLevel() {
      _builder.clearBatteryLevel()
    }

    /**
     * `bool is_charging = 2 [json_name = "isCharging"];`
     */
    public var isCharging: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsCharging")
        get() = _builder.isCharging
      @kotlin.jvm.JvmName("setIsCharging")
        set(value) {
        _builder.isCharging = value
      }
    /**
     * `bool is_charging = 2 [json_name = "isCharging"];`
     */
    public fun clearIsCharging() {
      _builder.clearIsCharging()
    }

    /**
     * `.tandem.v1.NetworkType network_type = 3 [json_name = "networkType"];`
     */
    public var networkType: dev.tandem.protocol.v1.NetworkType
      @kotlin.jvm.JvmName("getNetworkType")
        get() = _builder.networkType
      @kotlin.jvm.JvmName("setNetworkType")
        set(value) {
        _builder.networkType = value
      }
    public var networkTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getNetworkTypeValue")
        get() = _builder.networkTypeValue
      @kotlin.jvm.JvmName("setNetworkTypeValue")
        set(value) {
        _builder.networkTypeValue = value
      }
    /**
     * `.tandem.v1.NetworkType network_type = 3 [json_name = "networkType"];`
     */
    public fun clearNetworkType() {
      _builder.clearNetworkType()
    }

    /**
     * ```
     * Signal strength, 0 (none) to 4 (full bars); meaningless (0) when network_type is
     * NETWORK_TYPE_OFFLINE.
     * ```
     *
     * `int32 signal_level = 4 [json_name = "signalLevel"];`
     */
    public var signalLevel: kotlin.Int
      @kotlin.jvm.JvmName("getSignalLevel")
        get() = _builder.signalLevel
      @kotlin.jvm.JvmName("setSignalLevel")
        set(value) {
        _builder.signalLevel = value
      }
    /**
     * ```
     * Signal strength, 0 (none) to 4 (full bars); meaningless (0) when network_type is
     * NETWORK_TYPE_OFFLINE.
     * ```
     *
     * `int32 signal_level = 4 [json_name = "signalLevel"];`
     */
    public fun clearSignalLevel() {
      _builder.clearSignalLevel()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.DeviceStatus.copy(block: `dev.tandem.protocol.v1`.DeviceStatusKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.DeviceStatus =
  `dev.tandem.protocol.v1`.DeviceStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

