// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/files.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializefileChunk")
public inline fun fileChunk(block: dev.tandem.protocol.v1.FileChunkKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.FileChunk =
  dev.tandem.protocol.v1.FileChunkKt.Dsl._create(dev.tandem.protocol.v1.FileChunk.newBuilder()).apply { block() }._build()
/**
 * ```
 * FileChunk: PRD F-7.1, UC-15 — one fixed-size slice of the file named by `id`, sent only after
 * FileAccept. `seq` is 0-based and contiguous; `offset` MUST equal `seq * 262144`
 * (docs/protocol/SPEC.md #files-channel "Chunking"). `data` is capped at 262144 bytes (256 KiB) —
 * oversized payloads are a PROTOCOL_VIOLATION (docs/protocol/SPEC.md #files-channel "Chunking").
 * ```
 *
 * Protobuf type `tandem.v1.FileChunk`
 */
public object FileChunkKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.FileChunk.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.FileChunk.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.FileChunk = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `uint64 seq = 2 [json_name = "seq"];`
     */
    public var seq: kotlin.Long
      @kotlin.jvm.JvmName("getSeq")
        get() = _builder.seq
      @kotlin.jvm.JvmName("setSeq")
        set(value) {
        _builder.seq = value
      }
    /**
     * `uint64 seq = 2 [json_name = "seq"];`
     */
    public fun clearSeq() {
      _builder.clearSeq()
    }

    /**
     * `uint64 offset = 3 [json_name = "offset"];`
     */
    public var offset: kotlin.Long
      @kotlin.jvm.JvmName("getOffset")
        get() = _builder.offset
      @kotlin.jvm.JvmName("setOffset")
        set(value) {
        _builder.offset = value
      }
    /**
     * `uint64 offset = 3 [json_name = "offset"];`
     */
    public fun clearOffset() {
      _builder.clearOffset()
    }

    /**
     * `bytes data = 4 [json_name = "data"];`
     */
    public var data: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getData")
        get() = _builder.data
      @kotlin.jvm.JvmName("setData")
        set(value) {
        _builder.data = value
      }
    /**
     * `bytes data = 4 [json_name = "data"];`
     */
    public fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.FileChunk.copy(block: `dev.tandem.protocol.v1`.FileChunkKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.FileChunk =
  `dev.tandem.protocol.v1`.FileChunkKt.Dsl._create(this.toBuilder()).apply { block() }._build()

