// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/files.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializefileResumeRequest")
public inline fun fileResumeRequest(block: dev.tandem.protocol.v1.FileResumeRequestKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.FileResumeRequest =
  dev.tandem.protocol.v1.FileResumeRequestKt.Dsl._create(dev.tandem.protocol.v1.FileResumeRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * FileResumeRequest: PRD F-7.1, UC-15 — the receiver asks the sender to resume a previously
 * interrupted transfer named by `id` starting at `from_offset`, computed as the receiver's
 * retained temp file length rounded down to a 262144-byte boundary (docs/protocol/SPEC.md
 * #files-channel "Resume"). Retained temp files expire 24 h after their last write; a resume
 * request for an id whose temp file has expired or never existed gets FileReject
 * UNKNOWN_TRANSFER.
 * ```
 *
 * Protobuf type `tandem.v1.FileResumeRequest`
 */
public object FileResumeRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.FileResumeRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.FileResumeRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.FileResumeRequest = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `uint64 from_offset = 2 [json_name = "fromOffset"];`
     */
    public var fromOffset: kotlin.Long
      @kotlin.jvm.JvmName("getFromOffset")
        get() = _builder.fromOffset
      @kotlin.jvm.JvmName("setFromOffset")
        set(value) {
        _builder.fromOffset = value
      }
    /**
     * `uint64 from_offset = 2 [json_name = "fromOffset"];`
     */
    public fun clearFromOffset() {
      _builder.clearFromOffset()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.FileResumeRequest.copy(block: `dev.tandem.protocol.v1`.FileResumeRequestKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.FileResumeRequest =
  `dev.tandem.protocol.v1`.FileResumeRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

