// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/media.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializemediaHello")
public inline fun mediaHello(block: dev.tandem.protocol.v1.MediaHelloKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.MediaHello =
  dev.tandem.protocol.v1.MediaHelloKt.Dsl._create(dev.tandem.protocol.v1.MediaHello.newBuilder()).apply { block() }._build()
/**
 * ```
 * MediaHello: phone -> Mac, the first frame on the media connection. A receiver MUST reject a
 * MediaHello whose `ticket` is absent or not exactly 32 bytes (TICKET_REJECTED, local reason
 * MISSING) before comparing it against anything and before reading any further frame.
 * ```
 *
 * Protobuf type `tandem.v1.MediaHello`
 */
public object MediaHelloKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.MediaHello.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.MediaHello.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.MediaHello = _builder.build()

    /**
     * ```
     * Exactly 32 bytes (256 bits) as issued in MediaTicketGrant.ticket.
     * ```
     *
     * `bytes ticket = 1 [json_name = "ticket"];`
     */
    public var ticket: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getTicket")
        get() = _builder.ticket
      @kotlin.jvm.JvmName("setTicket")
        set(value) {
        _builder.ticket = value
      }
    /**
     * ```
     * Exactly 32 bytes (256 bits) as issued in MediaTicketGrant.ticket.
     * ```
     *
     * `bytes ticket = 1 [json_name = "ticket"];`
     */
    public fun clearTicket() {
      _builder.clearTicket()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.MediaHello.copy(block: `dev.tandem.protocol.v1`.MediaHelloKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.MediaHello =
  `dev.tandem.protocol.v1`.MediaHelloKt.Dsl._create(this.toBuilder()).apply { block() }._build()

