// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/control.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializemediaTicketGrant")
public inline fun mediaTicketGrant(block: dev.tandem.protocol.v1.MediaTicketGrantKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.MediaTicketGrant =
  dev.tandem.protocol.v1.MediaTicketGrantKt.Dsl._create(dev.tandem.protocol.v1.MediaTicketGrant.newBuilder()).apply { block() }._build()
/**
 * ```
 * MediaTicketGrant: docs/protocol/SPEC.md #media-ticket (docs/planning/decisions.md D-65). Sent
 * over CONTROL by the issuing side when a media connection is requested; binds the (separately
 * authenticated, full mTLS) media connection to this control session.
 * ```
 *
 * Protobuf type `tandem.v1.MediaTicketGrant`
 */
public object MediaTicketGrantKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.MediaTicketGrant.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.MediaTicketGrant.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.MediaTicketGrant = _builder.build()

    /**
     * ```
     * Exactly 32 bytes (256 bits), generated by a CSPRNG for every issuance. A receiver MUST
     * reject a presented ticket of any other length (MISSING) before comparing it to anything.
     * ```
     *
     * `bytes ticket = 1 [json_name = "ticket"];`
     */
    public var ticket: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getTicket")
        get() = _builder.ticket
      @kotlin.jvm.JvmName("setTicket")
        set(value) {
        _builder.ticket = value
      }
    /**
     * ```
     * Exactly 32 bytes (256 bits), generated by a CSPRNG for every issuance. A receiver MUST
     * reject a presented ticket of any other length (MISSING) before comparing it to anything.
     * ```
     *
     * `bytes ticket = 1 [json_name = "ticket"];`
     */
    public fun clearTicket() {
      _builder.clearTicket()
    }

    /**
     * ```
     * Milliseconds since the Unix epoch (UTC), 30 s after the moment of issuance, per the
     * issuer's own clock. The requesting side MUST NOT trust this value for its own deadline: it
     * computes its own deadline as the instant it received this message plus 30 s, measured on
     * its own monotonic clock, since this field accounts for neither delivery delay nor clock
     * skew between the two devices.
     * ```
     *
     * `int64 expires_at = 2 [json_name = "expiresAt"];`
     */
    public var expiresAt: kotlin.Long
      @kotlin.jvm.JvmName("getExpiresAt")
        get() = _builder.expiresAt
      @kotlin.jvm.JvmName("setExpiresAt")
        set(value) {
        _builder.expiresAt = value
      }
    /**
     * ```
     * Milliseconds since the Unix epoch (UTC), 30 s after the moment of issuance, per the
     * issuer's own clock. The requesting side MUST NOT trust this value for its own deadline: it
     * computes its own deadline as the instant it received this message plus 30 s, measured on
     * its own monotonic clock, since this field accounts for neither delivery delay nor clock
     * skew between the two devices.
     * ```
     *
     * `int64 expires_at = 2 [json_name = "expiresAt"];`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.MediaTicketGrant.copy(block: `dev.tandem.protocol.v1`.MediaTicketGrantKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.MediaTicketGrant =
  `dev.tandem.protocol.v1`.MediaTicketGrantKt.Dsl._create(this.toBuilder()).apply { block() }._build()

