// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/notify.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializenotificationDismiss")
public inline fun notificationDismiss(block: dev.tandem.protocol.v1.NotificationDismissKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.NotificationDismiss =
  dev.tandem.protocol.v1.NotificationDismissKt.Dsl._create(dev.tandem.protocol.v1.NotificationDismiss.newBuilder()).apply { block() }._build()
/**
 * ```
 * NotificationDismiss: PRD F-5.3 — either side sends this when a notification is dismissed, so
 * the other side removes its copy. `origin` records which side dismissed it, so the receiver
 * never re-forwards a dismissal it only just applied locally (avoiding an echo loop, E30-10,
 * E30-18).
 * ```
 *
 * Protobuf type `tandem.v1.NotificationDismiss`
 */
public object NotificationDismissKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.NotificationDismiss.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.NotificationDismiss.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.NotificationDismiss = _builder.build()

    /**
     * `string key = 1 [json_name = "key"];`
     */
    public var key: kotlin.String
      @kotlin.jvm.JvmName("getKey")
        get() = _builder.key
      @kotlin.jvm.JvmName("setKey")
        set(value) {
        _builder.key = value
      }
    /**
     * `string key = 1 [json_name = "key"];`
     */
    public fun clearKey() {
      _builder.clearKey()
    }

    /**
     * `.tandem.v1.NotificationDismiss.Origin origin = 2 [json_name = "origin"];`
     */
    public var origin: dev.tandem.protocol.v1.NotificationDismiss.Origin
      @kotlin.jvm.JvmName("getOrigin")
        get() = _builder.origin
      @kotlin.jvm.JvmName("setOrigin")
        set(value) {
        _builder.origin = value
      }
    public var originValue: kotlin.Int
      @kotlin.jvm.JvmName("getOriginValue")
        get() = _builder.originValue
      @kotlin.jvm.JvmName("setOriginValue")
        set(value) {
        _builder.originValue = value
      }
    /**
     * `.tandem.v1.NotificationDismiss.Origin origin = 2 [json_name = "origin"];`
     */
    public fun clearOrigin() {
      _builder.clearOrigin()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.NotificationDismiss.copy(block: `dev.tandem.protocol.v1`.NotificationDismissKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.NotificationDismiss =
  `dev.tandem.protocol.v1`.NotificationDismissKt.Dsl._create(this.toBuilder()).apply { block() }._build()

