// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/notify.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializenotificationActionResult")
public inline fun notificationActionResult(block: dev.tandem.protocol.v1.NotificationActionResultKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.NotificationActionResult =
  dev.tandem.protocol.v1.NotificationActionResultKt.Dsl._create(dev.tandem.protocol.v1.NotificationActionResult.newBuilder()).apply { block() }._build()
/**
 * ```
 * NotificationActionResult: PRD F-5.2 — the phone answers every received NotificationAction with
 * this, so the Mac can report a reply/action as sent, or "no longer available" if the source
 * notification was already gone (UC-09 alternate).
 * ```
 *
 * Protobuf type `tandem.v1.NotificationActionResult`
 */
public object NotificationActionResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.NotificationActionResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.NotificationActionResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.NotificationActionResult = _builder.build()

    /**
     * `string key = 1 [json_name = "key"];`
     */
    public var key: kotlin.String
      @kotlin.jvm.JvmName("getKey")
        get() = _builder.key
      @kotlin.jvm.JvmName("setKey")
        set(value) {
        _builder.key = value
      }
    /**
     * `string key = 1 [json_name = "key"];`
     */
    public fun clearKey() {
      _builder.clearKey()
    }

    /**
     * `.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];`
     */
    public var status: dev.tandem.protocol.v1.NotificationActionResult.Status
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.tandem.v1.NotificationActionResult.Status status = 2 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.NotificationActionResult.copy(block: `dev.tandem.protocol.v1`.NotificationActionResultKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.NotificationActionResult =
  `dev.tandem.protocol.v1`.NotificationActionResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

