// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/pairing.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializerevoke")
public inline fun revoke(block: dev.tandem.protocol.v1.RevokeKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.Revoke =
  dev.tandem.protocol.v1.RevokeKt.Dsl._create(dev.tandem.protocol.v1.Revoke.newBuilder()).apply { block() }._build()
/**
 * ```
 * Revoke: docs/protocol/SPEC.md #pairing "Mutual confirmation". Always means "delete the record
 * of the peer authenticated on this session"; can never name another peer, so it has no fields.
 * ```
 *
 * Protobuf type `tandem.v1.Revoke`
 */
public object RevokeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.Revoke.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.Revoke.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.Revoke = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.Revoke.copy(block: `dev.tandem.protocol.v1`.RevokeKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.Revoke =
  `dev.tandem.protocol.v1`.RevokeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

