// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/rotation.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializerotationChallenge")
public inline fun rotationChallenge(block: dev.tandem.protocol.v1.RotationChallengeKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.RotationChallenge =
  dev.tandem.protocol.v1.RotationChallengeKt.Dsl._create(dev.tandem.protocol.v1.RotationChallenge.newBuilder()).apply { block() }._build()
/**
 * ```
 * RotationChallenge: docs/protocol/SPEC.md #channel-binding-cb (docs/planning/decisions.md D-67,
 * D-74). Each side sends exactly one, unsolicited, immediately once its control session reaches
 * Ready; valid only on that session and for exactly one KeyRotation. Same shape as PairChallenge.
 * ```
 *
 * Protobuf type `tandem.v1.RotationChallenge`
 */
public object RotationChallengeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.RotationChallenge.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.RotationChallenge.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.RotationChallenge = _builder.build()

    /**
     * ```
     * Exactly 32 bytes (256 bits) from a CSPRNG, generated fresh per session. This is `cb` in the
     * KeyRotation transcript.
     * ```
     *
     * `bytes challenge = 1 [json_name = "challenge"];`
     */
    public var challenge: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getChallenge")
        get() = _builder.challenge
      @kotlin.jvm.JvmName("setChallenge")
        set(value) {
        _builder.challenge = value
      }
    /**
     * ```
     * Exactly 32 bytes (256 bits) from a CSPRNG, generated fresh per session. This is `cb` in the
     * KeyRotation transcript.
     * ```
     *
     * `bytes challenge = 1 [json_name = "challenge"];`
     */
    public fun clearChallenge() {
      _builder.clearChallenge()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.RotationChallenge.copy(block: `dev.tandem.protocol.v1`.RotationChallengeKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.RotationChallenge =
  `dev.tandem.protocol.v1`.RotationChallengeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

