// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/input.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializesetText")
public inline fun setText(block: dev.tandem.protocol.v1.SetTextKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.SetText =
  dev.tandem.protocol.v1.SetTextKt.Dsl._create(dev.tandem.protocol.v1.SetText.newBuilder()).apply { block() }._build()
/**
 * ```
 * SetText: replaces the focused field's text; at most 4096 characters.
 * ```
 *
 * Protobuf type `tandem.v1.SetText`
 */
public object SetTextKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.SetText.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.SetText.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.SetText = _builder.build()

    /**
     * `string text = 1 [json_name = "text"];`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `string text = 1 [json_name = "text"];`
     */
    public fun clearText() {
      _builder.clearText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.SetText.copy(block: `dev.tandem.protocol.v1`.SetTextKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.SetText =
  `dev.tandem.protocol.v1`.SetTextKt.Dsl._create(this.toBuilder()).apply { block() }._build()

