// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tandem/v1/sms.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package dev.tandem.protocol.v1;

@kotlin.jvm.JvmName("-initializesimList")
public inline fun simList(block: dev.tandem.protocol.v1.SimListKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.SimList =
  dev.tandem.protocol.v1.SimListKt.Dsl._create(dev.tandem.protocol.v1.SimList.newBuilder()).apply { block() }._build()
/**
 * ```
 * SimList: phone -> Mac, the active SIM subscriptions. Published on connect and whenever the
 * set changes (docs/protocol/SPEC.md #sms-channel "SIM list").
 * ```
 *
 * Protobuf type `tandem.v1.SimList`
 */
public object SimListKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: dev.tandem.protocol.v1.SimList.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: dev.tandem.protocol.v1.SimList.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): dev.tandem.protocol.v1.SimList = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SubscriptionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .tandem.v1.SimList.Subscription subscriptions = 1 [json_name = "subscriptions"];`
     */
     public val subscriptions: com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.SimList.Subscription, SubscriptionsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.subscriptionsList
      )
    /**
     * `repeated .tandem.v1.SimList.Subscription subscriptions = 1 [json_name = "subscriptions"];`
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.SimList.Subscription, SubscriptionsProxy>.add(value: dev.tandem.protocol.v1.SimList.Subscription) {
      _builder.addSubscriptions(value)
    }
    /**
     * `repeated .tandem.v1.SimList.Subscription subscriptions = 1 [json_name = "subscriptions"];`
     * @param value The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSubscriptions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.SimList.Subscription, SubscriptionsProxy>.plusAssign(value: dev.tandem.protocol.v1.SimList.Subscription) {
      add(value)
    }
    /**
     * `repeated .tandem.v1.SimList.Subscription subscriptions = 1 [json_name = "subscriptions"];`
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.SimList.Subscription, SubscriptionsProxy>.addAll(values: kotlin.collections.Iterable<dev.tandem.protocol.v1.SimList.Subscription>) {
      _builder.addAllSubscriptions(values)
    }
    /**
     * `repeated .tandem.v1.SimList.Subscription subscriptions = 1 [json_name = "subscriptions"];`
     * @param values The subscriptions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSubscriptions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.SimList.Subscription, SubscriptionsProxy>.plusAssign(values: kotlin.collections.Iterable<dev.tandem.protocol.v1.SimList.Subscription>) {
      addAll(values)
    }
    /**
     * `repeated .tandem.v1.SimList.Subscription subscriptions = 1 [json_name = "subscriptions"];`
     * @param index The index to set the value at.
     * @param value The subscriptions to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSubscriptions")
    public operator fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.SimList.Subscription, SubscriptionsProxy>.set(index: kotlin.Int, value: dev.tandem.protocol.v1.SimList.Subscription) {
      _builder.setSubscriptions(index, value)
    }
    /**
     * `repeated .tandem.v1.SimList.Subscription subscriptions = 1 [json_name = "subscriptions"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSubscriptions")
    public fun com.google.protobuf.kotlin.DslList<dev.tandem.protocol.v1.SimList.Subscription, SubscriptionsProxy>.clear() {
      _builder.clearSubscriptions()
    }
  }
  @kotlin.jvm.JvmName("-initializesubscription")
  public inline fun subscription(block: dev.tandem.protocol.v1.SimListKt.SubscriptionKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.SimList.Subscription =
    dev.tandem.protocol.v1.SimListKt.SubscriptionKt.Dsl._create(dev.tandem.protocol.v1.SimList.Subscription.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `tandem.v1.SimList.Subscription`
   */
  public object SubscriptionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: dev.tandem.protocol.v1.SimList.Subscription.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: dev.tandem.protocol.v1.SimList.Subscription.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): dev.tandem.protocol.v1.SimList.Subscription = _builder.build()

      /**
       * `int32 subscription_id = 1 [json_name = "subscriptionId"];`
       */
      public var subscriptionId: kotlin.Int
        @kotlin.jvm.JvmName("getSubscriptionId")
          get() = _builder.subscriptionId
        @kotlin.jvm.JvmName("setSubscriptionId")
          set(value) {
          _builder.subscriptionId = value
        }
      /**
       * `int32 subscription_id = 1 [json_name = "subscriptionId"];`
       */
      public fun clearSubscriptionId() {
        _builder.clearSubscriptionId()
      }

      /**
       * `string display_name = 2 [json_name = "displayName"];`
       */
      public var displayName: kotlin.String
        @kotlin.jvm.JvmName("getDisplayName")
          get() = _builder.displayName
        @kotlin.jvm.JvmName("setDisplayName")
          set(value) {
          _builder.displayName = value
        }
      /**
       * `string display_name = 2 [json_name = "displayName"];`
       */
      public fun clearDisplayName() {
        _builder.clearDisplayName()
      }

      /**
       * `int32 slot_index = 3 [json_name = "slotIndex"];`
       */
      public var slotIndex: kotlin.Int
        @kotlin.jvm.JvmName("getSlotIndex")
          get() = _builder.slotIndex
        @kotlin.jvm.JvmName("setSlotIndex")
          set(value) {
          _builder.slotIndex = value
        }
      /**
       * `int32 slot_index = 3 [json_name = "slotIndex"];`
       */
      public fun clearSlotIndex() {
        _builder.clearSlotIndex()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.SimList.copy(block: `dev.tandem.protocol.v1`.SimListKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.SimList =
  `dev.tandem.protocol.v1`.SimListKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun dev.tandem.protocol.v1.SimList.Subscription.copy(block: `dev.tandem.protocol.v1`.SimListKt.SubscriptionKt.Dsl.() -> kotlin.Unit): dev.tandem.protocol.v1.SimList.Subscription =
  `dev.tandem.protocol.v1`.SimListKt.SubscriptionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

